'use strict';

/*
 * Item 6.10 — the plan's baseline must be GENERATED, not hand-copied.
 *
 * docs/README.md records six improvement documents that were retired because they
 * stated numbers that were wrong when they were written and wrong when they were
 * deleted: three different line counts for studio/main.mjs, three different IPC
 * channel counts. docs/IMPROVEMENTS.md is now the single canonical plan, and item
 * 6.10 is the admission that the same rot will happen again while the baseline is
 * copied by hand.
 *
 * These tests pin three things:
 *   1. the comparison logic itself — stale, missing and unknown rows are all
 *      caught, and a correct table passes
 *   2. the REAL plan in this repository — its generated block agrees with the
 *      tree, and it degrades in the documented way when a measured file moves
 *   3. the Status-at-a-Glance counts, which are generated by the same reasoning
 *
 * The tests read the actual docs/IMPROVEMENTS.md and the actual source files, so
 * they fail for the same reason CI would.
 */

const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const {
  METRICS, START, END, PLAN_FILE,
  measure, renderTable, parseTable, compareTables, check, applyTable, describe,
} = require('../../tools/check-plan-baseline.cjs');
const { countStatuses, statusOf } = require('../../tools/count-plan-status.cjs');

const planText = () => fs.readFileSync(PLAN_FILE, 'utf8');
const NL = String.fromCharCode(10);

// ---------------------------------------------------------------------------
// 1. Comparison logic
// ---------------------------------------------------------------------------

test('a table that matches the measurement passes', () => {
  const table = renderTable(new Map([['a', 5], ['b', 1234]]));
  assert.ok(table.includes('| `b` | 1,234 |'), 'four-digit values are grouped for readability');
  const parsed = parseTable(table);
  assert.equal(parsed.get('a'), 5);
  assert.equal(parsed.get('b'), 1234, 'thousands separators are parsed back out, not treated as text');
  const diff = compareTables(new Map([['a', 5], ['b', 1234]]), parsed);
  assert.equal(diff.ok, true);
  assert.deepEqual(diff.stale, []);
  assert.deepEqual(diff.unknown, []);
  assert.deepEqual(diff.missing, []);
});

test('a stale value is reported with both numbers, so the fix is unambiguous', () => {
  const documented = parseTable(renderTable(new Map([['studio/main.mjs lines', 4116]])));
  const diff = compareTables(new Map([['studio/main.mjs lines', 4117]]), documented);
  assert.equal(diff.ok, false);
  assert.deepEqual(diff.stale, [{ id: 'studio/main.mjs lines', documented: 4116, measured: 4117 }]);
  assert.match(describe(diff), /plan says 4,116, tree has 4,117/);
});

test('a row nothing measures any more is reported, not silently ignored', () => {
  /* A table that keeps a row for a metric that no longer exists is as misleading
   * as one holding a stale number, so it must fail too. */
  const documented = parseTable(renderTable(new Map([['gone', 1]])));
  const diff = compareTables(new Map([['a', 5]]), documented);
  assert.equal(diff.ok, false);
  assert.deepEqual(diff.unknown, [{ id: 'gone', value: 1 }]);
  assert.deepEqual(diff.missing, [{ id: 'a', value: 5 }]);
});

test('a missing or malformed block is refused rather than read as zero', () => {
  assert.equal(parseTable(''), null);
  assert.equal(parseTable('no markers here'), null);
  assert.equal(parseTable([START, 'no rows', END].join(NL)), null, 'an empty block is not a valid table');
  const result = check({ planText: 'a plan with no baseline block' });
  assert.equal(result.ok, false);
  assert.equal(result.reason, 'missing-baseline');
  assert.match(result.message, /--write/, 'the failure tells the reader how to fix it');
});

test('applyTable replaces the block in place and leaves the rest of the plan alone', () => {
  const original = ['intro', '', START, '| Metric | Value |', '| --- | --- |', '| `a` | 1 |', END, '', 'outro', ''].join(NL);
  const updated = applyTable(original, renderTable(new Map([['a', 99]])));
  assert.ok(updated.startsWith('intro'), 'text before the block is untouched');
  assert.ok(updated.endsWith('outro' + NL), 'text after the block is untouched');
  assert.ok(updated.includes('| `a` | 99 |'));
  assert.equal(updated.split(START).length - 1, 1, 'exactly one block survives');
  assert.equal(applyTable(updated, renderTable(new Map([['a', 99]]))), updated, 'idempotent');
});

test('every metric is a callable measurement with a unique, stable id', () => {
  assert.ok(METRICS.length >= 8, 'the baseline covers the surfaces the plan argues about');
  const ids = METRICS.map(m => m.id);
  assert.equal(new Set(ids).size, ids.length, 'ids are unique');
  const values = measure();
  assert.equal(values.size, METRICS.length);
  for (const [id, value] of values) {
    assert.ok(Number.isInteger(value) && value > 0, `${id} measured a real count (got ${value})`);
  }
});

// ---------------------------------------------------------------------------
// 2. The real plan in this repository
// ---------------------------------------------------------------------------

test('the committed plan baseline is current', () => {
  const result = check();
  assert.equal(result.ok, true, `docs/IMPROVEMENTS.md is ${result.reason}: ${JSON.stringify({
    stale: result.stale, missing: result.missing, unknown: result.unknown,
  })}`);
});

test('the plan really carries the generated block, in the documented place', () => {
  const text = planText();
  assert.ok(text.includes(START) && text.includes(END), 'both markers are present');
  assert.ok(text.indexOf(START) < text.indexOf('## Verification'),
    'the baseline sits with the other measured material, before Verification');
  /* Markers appear exactly once each, or the reader cannot tell which is real. */
  assert.equal(text.split(START).length - 1, 1);
  assert.equal(text.split(END).length - 1, 1);
});

test('the done-check item 6.10 asks for: one extra line fails the check', () => {
  /*
   * The plan states its own done-check: "changing studio/main.mjs by one line
   * without updating the prose fails a check". Simulate that exactly — measure a
   * tree in which main.mjs is one line longer — and prove the comparison catches
   * it. This is the assertion the whole item exists for.
   */
  const measured = measure();
  assert.equal(check().ok, true, 'the committed table is current before we perturb anything');
  const bumped = new Map(measured);
  bumped.set('studio/main.mjs lines', measured.get('studio/main.mjs lines') + 1);
  const diff = compareTables(bumped, parseTable(planText()));
  assert.equal(diff.ok, false, 'a one-line drift must fail the check');
  assert.deepEqual(diff.stale.map(row => row.id), ['studio/main.mjs lines']);
  assert.equal(diff.stale[0].measured - diff.stale[0].documented, 1);
});

test('the generator agrees with the tree it just measured', () => {
  /*
   * The strongest anti-rot property: re-rendering the table from the live tree
   * must reproduce the committed block byte for byte. If this fails, someone
   * edited the block by hand.
   */
  const text = planText();
  const from = text.indexOf(START);
  const to = text.indexOf(END) + END.length;
  assert.equal(text.slice(from, to), renderTable(measure()), 'the committed block is exactly what the generator produces');
});

// ---------------------------------------------------------------------------
// 3. The Status-at-a-Glance counts (generated by the same reasoning)
// ---------------------------------------------------------------------------

test('item rows are classified by their status cell, not by prose anywhere in the row', () => {
  assert.equal(statusOf('| 2.8 | **Rate-limit outbound agent requests** | DONE | evidence |'), 'DONE');
  assert.equal(statusOf('| 4.10 | Parse coverage | DONE | x |'), 'DONE');
  assert.equal(statusOf('| 5.7 | macOS notarization | TODO (needs credentials) |'), 'TODO');
  assert.equal(statusOf('| 3.1 | **Split main.mjs** | PARTIAL |'), 'PARTIAL');
  /* A row that MENTIONS a status in its evidence cell is not that status. Only
   * the status cell is consulted, so evidence reading "... was TODO before this
   * change" must not flip the row. */
  assert.equal(statusOf('| 1.7 | Something | DONE | it was TODO before |'), 'DONE');
  assert.equal(statusOf('| 1.7 | Something | UNKNOWN | x |'), null, 'an unrecognised status is unclassified, not guessed');
});

test('only numbered item rows are counted, never headings or the exec summary', () => {
  const sample = [
    '| 1.1 | a | DONE |',
    '| Phase 1 — Quick Wins |',
    '| Status | Count | What it means |',
    '| **DONE** | 21 | Implemented |',
    '| 1.2 | b | TODO |',
  ].join(NL);
  const result = countStatuses(sample);
  assert.equal(result.items, 2, 'the exec-summary row must not be counted as an item');
  assert.deepEqual(result.counts, { DONE: 1, PARTIAL: 0, TODO: 1 });
});

test('every item row in the real plan is classified — no silent gaps', () => {
  const result = countStatuses();
  assert.ok(result.items >= 60, `the plan still publishes its phased items (got ${result.items})`);
  assert.deepEqual(result.unclassified, [], 'an unclassified row would vanish from the totals');
  assert.equal(result.counts.DONE + result.counts.PARTIAL + result.counts.TODO, result.items);
});

/* Read a `| **STATUS** | N |` summary row out of the plan's opening table. */
function summaryCount(text, status) {
  for (const line of String(text).split(NL)) {
    const cells = line.split('|').map(cell => cell.trim().replace(/\*/g, ''));
    if (cells.length >= 4 && cells[1] === status) {
      const value = Number(cells[2].replace(/[,\s]/g, ''));
      if (Number.isInteger(value)) return value;
    }
  }
  return null;
}

test('the plan publishes the generated counts, not hand-written ones', () => {
  /*
   * The whole point of 6.10: the numbers in the prose are the numbers the tool
   * produces. If someone flips a status without updating the summary, this fails
   * instead of the plan quietly lying.
   */
  const result = countStatuses();
  const text = planText();
  for (const status of ['DONE', 'PARTIAL', 'TODO']) {
    assert.equal(summaryCount(text, status), result.counts[status],
      `the Status-at-a-Glance ${status} count must equal the items that say ${status}`);
  }
});

test('the plan is still the single document that states these numbers', () => {
  /*
   * Item 6.4 collapsed six plans into one; item 6.10 keeps its numbers honest.
   * Both are defeated by a second document reintroducing its own counts, so the
   * archived plans must stay archived.
   */
  const docs = fs.readdirSync(path.dirname(PLAN_FILE));
  const top = docs.filter(name => /^IMPROVEMENTS.*\.md$/.test(name));
  assert.deepEqual(top, ['IMPROVEMENTS.md'], `only one improvement plan may live in docs/ (found ${top.join(', ')})`);
});
