'use strict';

/* Parsers for the TypeScript/JavaScript toolchain the PRD names explicitly
 * (ESLint, tsc, Jest, Vitest).
 *
 * Every fixture in fixtures-ts-toolchain.json is VERBATIM output captured by
 * running the real tools (typescript 5, eslint 8, jest 29, vitest 1) against a
 * deliberately broken fixture. That matters: three of the four parsers were
 * wrong against my recollection of the formats and only became correct when
 * checked against real output —
 *   - tsc pretty output carries ANSI colour codes even when piped, so every
 *     diagnostic regex matched nothing and the parser returned ZERO failures
 *     while the summary still counted 2. In the loop that is a false green.
 *   - ESLint indents each problem line under its file header; matching the
 *     anchored patterns against the raw line dropped all 7 diagnostics.
 *   - Vitest prints each failure TWICE (compact list + detail block), so a
 *     naive parser reported 7 failures for 2 real ones, and treated the
 *     per-file header and the `❯ file:4:54` reference as test names.
 * Fixtures preserve those properties exactly (ANSI escapes, CRLF vs LF, and the
 * duplicate listings), so a regression in stripping or dedupe fails here.
 */
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const T = require('../agent/test-loop.cjs');

const FIXTURES = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'fixtures-ts-toolchain.json'), 'utf8'));
const fx = (name) => FIXTURES[name];

test('fixtures are real tool output, not hand-written expectations', () => {
  // ANSI escapes and CRLF are the properties that broke the first drafts, so
  // assert the fixtures still carry them: a fixture regenerated by hand-typing
  // would silently stop covering those paths.
  assert.ok(fx('tsc-pretty').includes('\u001b['), 'tsc pretty fixture carries ANSI colour codes');
  assert.ok(fx('tsc-pretty').includes('\r\n'), 'tsc fixture carries CRLF line endings');
  assert.ok(fx('jest').includes('●'), 'jest fixture carries the failure marker');
  assert.ok((fx('vitest').match(/FAIL/g) || []).length >= 2, 'vitest fixture carries duplicate listings');
});

/* ---------------------------------------------------------------------- tsc */

test('tsc pretty output: ANSI stripped, file/line/col and error code captured', () => {
  const p = T.parseTscOutput(fx('tsc-pretty'), '');
  assert.equal(p.parser, 'tsc');
  assert.equal(p.failures.length, 2, 'both diagnostics parsed despite ANSI codes');
  assert.equal(p.counts.fail, 2);

  const [f0, f1] = p.failures;
  assert.equal(f0.file.path, 'src/bad.ts');
  assert.deepEqual([f0.file.line, f0.file.column], [4, 7]);
  assert.equal(f0.code, 'TS2322');
  assert.equal(f0.severity, 'error');
  assert.match(f0.message, /not assignable/);
  assert.equal(f1.code, 'TS2339');
  assert.equal(f1.file.line, 5);
  assert.match(f1.message, /naem/);

  // The source echo and caret line tsc prints under each diagnostic must not
  // become diagnostics, nor bloat the message.
  assert.ok(!p.failures.some(f => /let n: number|~~~|\d+\s*\|/.test(f.name)), 'no source echo as a diagnostic');
  assert.ok(p.failures.every(f => !/~/.test(f.message)), 'message free of caret noise');
});

test('tsc classic (--pretty false) parses path(line,col)', () => {
  const p = T.parseTscOutput(fx('tsc-classic'), '');
  assert.equal(p.failures.length, 2);
  const f0 = p.failures[0];
  assert.equal(f0.file.path, 'src/bad.ts');
  assert.deepEqual([f0.file.line, f0.file.column], [4, 7]);
  assert.equal(f0.code, 'TS2322');
});

test('tsc with no diagnostics reports zero, and a project-wide error has no file', () => {
  assert.equal(T.parseTscOutput('Done in 1.2s.\n', '').failures.length, 0);
  const p = T.parseTscOutput('error TS5057: The specified path does not exist.\n', '');
  assert.equal(p.failures.length, 1);
  assert.equal(p.failures[0].file, null);
  assert.equal(p.failures[0].code, 'TS5057');
});

/* ------------------------------------------------------------------- eslint */

test('eslint stylish: every problem captured with file, rule id and fixable count', () => {
  const p = T.parseEslintOutput(fx('eslint-stylish'), '');
  assert.equal(p.parser, 'eslint');
  assert.equal(p.failures.length, 7, 'all seven problems parsed');
  assert.equal(p.counts.fail, 7);
  assert.equal(p.counts.warnings, 0);
  // The loop uses this to decide whether a quick-fix pass can help at all.
  assert.equal(p.counts.fixable, 4, 'fixable count read from the --fix summary');

  const f0 = p.failures[0];
  assert.deepEqual([f0.file.line, f0.file.column], [1, 7]);
  assert.equal(f0.code, 'no-unused-vars');
  assert.equal(f0.severity, 'error');
  assert.match(f0.message, /unused/);
  assert.match(f0.file.path, /bad\.js$/, 'absolute file path attached to each problem');
  assert.equal(new Set(p.failures.map(f => f.file.path)).size, 1, 'all problems attributed to one file');
  assert.ok(p.failures.some(f => f.code === 'semi'), 'rule ids distinguished per problem');
});

test('eslint compact: same diagnostics, rule id present', () => {
  const p = T.parseEslintOutput(fx('eslint-compact'), '');
  assert.equal(p.failures.length, 7);
  const f0 = p.failures[0];
  assert.deepEqual([f0.file.line, f0.file.column], [1, 7]);
  // A lazy `.+?` before an optional `(rule)` group used to let the message
  // swallow the rule id, so compact output reported `code: null` throughout.
  assert.equal(f0.code, 'no-unused-vars');
  assert.ok(p.failures.every(f => f.code), 'every compact diagnostic keeps its rule id');
});

test('eslint with no problems reports zero and is not confused by a clean run', () => {
  const p = T.parseEslintOutput('', '');
  assert.equal(p.failures.length, 0);
  assert.equal(p.counts.fixable, 0);
});

test('a warning-only eslint run counts warnings, not failures', () => {
  const out = [
    'C:\\proj\\src\\a.js',
    '  1:1  warning  Unexpected var, use let or no-prefer-const',
    '',
    '\u2716 1 problem (0 errors, 1 warning)',
  ].join('\n');
  const p = T.parseEslintOutput(out, '');
  assert.equal(p.failures.length, 1);
  assert.equal(p.failures[0].severity, 'warning');
  assert.equal(p.counts.warnings, 1);
  assert.equal(p.counts.fail, 0);
});

/* --------------------------------------------------------------------- jest */

test('jest: detail blocks parsed once each, counts from the summary', () => {
  // Jest writes results to STDERR, so pass stdout empty.
  const p = T.parseJestOutput('', fx('jest'));
  assert.equal(p.parser, 'jest');
  assert.equal(p.counts.fail, 2);
  assert.equal(p.counts.pass, 1);
  assert.equal(p.counts.tests, 3);
  // Two ● detail blocks exist; the inline `×` markers must not double them.
  assert.equal(p.failures.length, 2, 'one failure per detail block, not doubled');
  const names = p.failures.map(f => f.name);
  assert.ok(names.some(n => /adds two numbers/.test(n)), names.join(' | '));
  assert.ok(names.some(n => /handles zero/.test(n)), names.join(' | '));
});

test('jest: file/line/col come from the stack frame, message is the assertion only', () => {
  const p = T.parseJestOutput('', fx('jest'));
  const f0 = p.failures[0];
  assert.match(f0.file.path, /sum\.test\.js$/);
  assert.deepEqual([f0.file.line, f0.file.column], [3, 54]);
  assert.match(f0.message, /expect\(received\)\.toBe/);
  // The source gutter (`> 3 | test(...)`) and the caret line are context for a
  // human; folded into the message they bury the assertion the fixer needs.
  assert.ok(!/> \d \|/.test(f0.message), 'source echo excluded: ' + f0.message);
  assert.ok(!/\^/.test(f0.message), 'caret line excluded: ' + f0.message);
  assert.ok(!/- Expected|\+ Received/.test(f0.message), 'diff block excluded: ' + f0.message);
  assert.ok(!p.failures.some(f => /Object\.toBe/.test(f.name)), 'stack frames are not failures');
});

test('a passing jest run yields no failures and zero fail count', () => {
  const out = 'PASS ./a.test.js\nTests:       3 passed, 3 total\nTest Suites: 1 passed, 1 total\n';
  const p = T.parseJestOutput('', out);
  assert.equal(p.failures.length, 0);
  assert.equal(p.counts.fail, 0);
  assert.equal(p.counts.pass, 3);
});

/* ------------------------------------------------------------------- vitest */

test('vitest: the two layouts merge into one failure per test', () => {
  const p = T.parseVitestOutput(fx('vitest'), '');
  assert.equal(p.parser, 'vitest');
  assert.equal(p.counts.fail, 2);
  // The compact list AND the FAIL detail block both name each test; a parser
  // that took both verbatim reported 7 failures for 2 real ones.
  assert.equal(p.failures.length, 2, 'deduped: ' + JSON.stringify(p.failures.map(f => f.name)));
  assert.deepEqual(p.failures.map(f => f.name), ['sum › adds two numbers', 'sum › handles zero']);
});

test('vitest: non-failure ❯ lines are not treated as tests', () => {
  const p = T.parseVitestOutput(fx('vitest'), '');
  const names = p.failures.map(f => f.name);
  // The per-file header and the file reference are ❯-prefixed but are not tests.
  assert.ok(!names.some(n => /tests? \|/.test(n)), 'per-file header excluded: ' + names.join(' | '));
  assert.ok(!names.some(n => /^\S+\.[jt]sx?:\d+/.test(n)), 'file reference excluded: ' + names.join(' | '));
});

test('vitest: file reference supplies line, AssertionError wins over the → summary', () => {
  const p = T.parseVitestOutput(fx('vitest'), '');
  for (const f of p.failures) {
    assert.ok(f.file && /vsum\.test\.js$/.test(f.file.path), 'file attached: ' + JSON.stringify(f.file));
    assert.equal(typeof f.file.line, 'number', 'line from the ❯ file reference');
    assert.match(f.message, /^AssertionError:/, 'explicit error class preferred over → summary');
    assert.ok(!/- Expected|\+ Received|^[-+] \d/.test(f.message), 'diff block excluded: ' + f.message);
    assert.ok(!/\d\|/.test(f.message), 'source echo excluded: ' + f.message);
  }
  assert.equal(p.failures[0].file.line, 4);
});

/* ------------------------------------------------- shared normalization */

test('ANSI stripping is what makes colourised output parseable', () => {
  // Prove the mechanism rather than trusting the fixtures: the same diagnostic
  // with and without colour codes must parse identically.
  const plain = 'src/a.ts:3:1 - error TS2304: Cannot find name.\n';
  const coloured = '\u001b[96msrc/a.ts\u001b[0m:\u001b[93m3\u001b[0m:\u001b[93m1\u001b[0m - \u001b[91merror\u001b[0m\u001b[90m TS2304: \u001b[0mCannot find name.\n';
  const a = T.parseTscOutput(plain, '');
  const b = T.parseTscOutput(coloured, '');
  assert.equal(a.failures.length, 1);
  assert.equal(b.failures.length, 1, 'colourised output parses too');
  assert.equal(b.failures[0].code, 'TS2304');
  assert.deepEqual(a.failures[0].file, b.failures[0].file);
});

test('CRLF output parses the same as LF', () => {
  const lf = 'src/a.ts(3,1): error TS2304: Cannot find name.\n';
  const crlf = 'src/a.ts(3,1): error TS2304: Cannot find name.\r\n';
  assert.equal(T.parseTscOutput(lf, '').failures.length, 1);
  const p = T.parseTscOutput(crlf, '');
  assert.equal(p.failures.length, 1);
  assert.equal(p.failures[0].code, 'TS2304', 'a trailing \\r must not defeat the anchored pattern');
});

test('runners are reachable by name and unknown runners fall back to generic', () => {
  for (const name of ['jest', 'vitest', 'tsc', 'eslint', 'node', 'pytest']) {
    const out = T.interpret({ ok: false, exitCode: 1, stdout: '', stderr: '' }, name);
    assert.equal(out.runner.toLowerCase().includes(name.slice(0, 4).toLowerCase()) || out.runner.length > 0, true,
      name + ' resolves to a labelled runner, got ' + out.runner);
    assert.notEqual(out.parser, null);
  }
  assert.equal(T.interpret({ ok: true, exitCode: 0, stdout: 'x' }, 'some-bespoke-script').parser, 'generic');
});

test('every parser reports counts.fail as a number, even on a clean run', () => {
  // A parser that omits the field on success forces every caller to write
  // `counts.fail || 0`; one that returns undefined can render as "undefined
  // failures" in the UI. Verified per parser rather than assumed.
  const clean = {
    node: '# tests 3\n# pass 3\n# fail 0\n',
    pytest: '===== 3 passed in 0.05s =====\n',
    jest: 'PASS ./a.test.js\nTests:       3 passed, 3 total\n',
    vitest: ' Test Files  1 passed (1)\n      Tests  3 passed (3)\n',
    tsc: 'Done in 1.2s.\n',
    eslint: '',
  };
  const parse = {
    node: T.parseNodeTestOutput, pytest: T.parsePytestOutput, jest: (o, e) => T.parseJestOutput('', o),
    vitest: T.parseVitestOutput, tsc: T.parseTscOutput, eslint: T.parseEslintOutput,
  };
  for (const [name, out] of Object.entries(clean)) {
    const counts = parse[name](out, '').counts;
    assert.equal(typeof counts.fail, 'number', name + ' counts.fail is a number, got ' + JSON.stringify(counts));
    assert.equal(counts.fail, 0, name + ' clean run reports zero failures');
  }
});

test('interpret trusts the exit code over parseable-looking output', () => {
  // A tool that exits non-zero while printing clean output must not go green.
  const r = T.interpret({ ok: false, exitCode: 2, stdout: 'All checks passed.' }, 'tsc');
  assert.equal(r.ok, false);
  const ok = T.interpret({ ok: true, exitCode: 0, stdout: 'src/a.ts:1:1 - error TS1: x' }, 'tsc');
  assert.equal(ok.ok, true);
});
