#!/usr/bin/env python3
"""Regression checks for the homepage heuristic chat.
Requires Python Playwright + Chromium. Works with an offline HTML preview.
Usage: CHROMIUM_EXECUTABLE=/usr/bin/chromium python tests/chat_browser.py ../SignalREACH-preview.html
"""
import json, os, sys
from pathlib import Path
from playwright.sync_api import sync_playwright, expect
ROOT=Path(__file__).resolve().parents[1]
PREVIEW=Path(sys.argv[1]) if len(sys.argv)>1 else ROOT.parent/'SignalREACH-preview.html'
checks=[]; errors=[]; requests=[]; layouts=[]
def check(name,condition=True):
    assert condition,name
    checks.append(name)
with sync_playwright() as p:
    options={'headless':True}
    if os.environ.get('CHROMIUM_EXECUTABLE'): options['executable_path']=os.environ['CHROMIUM_EXECUTABLE']
    browser=p.chromium.launch(**options)
    page=browser.new_page(viewport={'width':1440,'height':1000},reduced_motion='reduce',color_scheme='dark',accept_downloads=True)
    page.set_default_timeout(5000)
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.on('request',lambda r:requests.append(r.url))
    page.set_content(PREVIEW.read_text(encoding='utf-8'),wait_until='load')
    def click(selector):page.locator(selector).first.click()
    def ask(text):
        page.locator('#demo-input').fill(text);click('[data-chat-send]')
        expect(page.locator('#demo-log')).to_have_attribute('aria-busy','false')
    def last_title():return page.locator('.chat-reply-title').last.inner_text()
    check('Chat initializes once',page.locator('.chat-panel[data-chat-ready="true"]').count()==1)
    check('Welcome shows catalog size','47 topics' in page.locator('#demo-log').inner_text())
    check('Four starter suggestions',page.locator('#demo-suggestions button').count()==4)
    click('[data-chat-topics-toggle]');expect(page.locator('#demo-topic-browser')).to_be_visible()
    check('Topic browser opens with all 47 topics',page.locator('[data-chat-topic]').count()==47)
    click('[data-chat-group="Troubleshoot"]')
    check('Category filter',page.locator('[data-chat-topic]').count()==6)
    page.locator('#demo-topic-search').fill('401')
    check('Topic search matches keyword',page.locator('[data-chat-topic]').count()==1)
    click('[data-chat-topic="authentication"]')
    expect(page.locator('#demo-topic-browser')).not_to_be_visible()
    check('Topic selection answers and closes browser',last_title()=='401 / 403 access errors')
    check('Follow-up suggestions appear',page.locator('#demo-suggestions button').count()==5)
    click('[data-chat-prompt="tell me more"]')
    check('More detail retains topic',last_title()=='401 / 403 access errors' and page.locator('.chat-turn').last.locator('.chat-steps li').count()==3)
    click('[data-chat-prompt="show an example"]')
    check('Examples retain topic',last_title()=='401 / 403 access errors' and page.locator('.chat-example').last.is_visible())
    ask('conect a modle');check('Typo-tolerant browser reply',last_title()=='Connect a model')
    ask('what next');check('Related topic follow-up',last_title()=='Model selection')
    page.locator('#demo-mode').select_option('steps');ask('agent teams')
    check('Selected detailed response style',page.locator('.chat-turn').last.locator('.chat-steps li').count()==3)
    page.locator('#demo-mode').select_option('example');ask('responsive website')
    check('Example style produces text-only code',page.locator('.chat-turn').last.locator('pre code').count()==1)
    page.locator('#demo-mode').select_option('quick')
    ask('<img src=x onerror="window.xss=true"> Tell me about themes')
    check('HTML-like input is never executed',page.evaluate('window.xss !== true') and page.locator('#demo-log img').count()==0)
    click('.chat-turn:last-child [data-chat-action="light"]')
    check('Light theme action',page.locator('html').get_attribute('data-theme')=='light')
    click('.chat-turn:last-child [data-chat-action="dark"]')
    check('Dark theme action',page.locator('html').get_attribute('data-theme')=='dark')
    click('.chat-turn:last-child [data-chat-action="theme-file"]')
    check('Sample file action',page.locator('#editor-file-name').inner_text()=='theme.css')
    click('.chat-turn:last-child [data-copy]')
    expect(page.locator('.toast')).to_have_class('toast visible');check('Copy reply gives feedback')
    with page.expect_download() as exported:click('[data-chat-export]')
    download=exported.value
    check('Transcript export has correct filename',download.suggested_filename=='SignalREACH-demo-chat.txt')
    transcript=Path(download.path()).read_text()
    check('Export includes the actual conversation','conect a modle' in transcript and 'Model selection' in transcript)
    ask('/topics');expect(page.locator('#demo-topic-browser')).to_be_visible()
    page.locator('#demo-topic-search').fill('no-such-topic-ever')
    check('No-results state is explicit','No matching topics' in page.locator('#demo-topic-list').inner_text())
    page.keyboard.press('Escape');expect(page.locator('#demo-topic-browser')).not_to_be_visible()
    check('Escape restores focus to Topics',page.locator('[data-chat-topics-toggle]').evaluate('(el)=>el===document.activeElement'))
    ask('the elephant dances on mars')
    check('Unknown question produces honest fallback','do not have a prepared answer' in page.locator('.chat-turn').last.inner_text())
    ask('/clear');check('Clear command resets transcript',page.locator('.chat-turn').count()==0)
    click('[data-chat-export]');check('Empty export gives feedback','Ask a question' in page.locator('.toast').inner_text())
    ask('/help');check('Help command lists commands','/topics' in page.locator('.chat-turn').last.inner_text())
    ask('/random');check('Random command answers a topic',bool(last_title()))
    ask('/steps');check('Steps command expands current topic',page.locator('.chat-turn').last.locator('.chat-steps').count()==1)
    ask('/example');check('Example command expands current topic',page.locator('.chat-turn').last.locator('.chat-example').count()==1)
    # Direct event dispatch checks guards independently of disabled controls.
    page.emulate_media(reduced_motion='no-preference')
    page.evaluate('document.documentElement.dataset.motion="on"')
    click('[data-chat-reset]')
    page.locator('#demo-input').fill('themes')
    page.evaluate('document.querySelector("#demo-form").requestSubmit()')
    expect(page.locator('#demo-log')).to_have_attribute('aria-busy','true')
    check('Stop control visible during animation',page.locator('[data-chat-stop]').is_visible())
    page.evaluate('document.querySelector("#demo-input").value="agent teams";document.querySelector("#demo-form").requestSubmit()')
    check('Rapid/Enter duplicate submission is ignored',page.locator('.chat-turn').count()==1)
    click('[data-chat-stop]');expect(page.locator('#demo-log')).to_have_attribute('aria-busy','false')
    before=page.locator('#demo-log .chat-message').last.inner_text();page.wait_for_timeout(700)
    check('Stop cancels pending typing',before==page.locator('#demo-log .chat-message').last.inner_text() and '[stopped]' in before)
    check('Draft typed while busy is preserved',page.locator('#demo-input').input_value()=='agent teams')
    page.locator('#demo-input').fill('website');page.evaluate('document.querySelector("#demo-form").requestSubmit()')
    click('[data-chat-reset]');page.wait_for_timeout(700)
    check('Reset during typing prevents stale replies',page.locator('.chat-turn').count()==0 and page.locator('[data-chat-send]').is_enabled())
    page.locator('#demo-input').fill('themes');page.evaluate('document.querySelector("#demo-form").requestSubmit()')
    page.locator('#demo-input').press('Escape');expect(page.locator('#demo-log')).to_have_attribute('aria-busy','false')
    check('Escape stops a reply','[stopped]' in page.locator('#demo-log .chat-message').last.inner_text())
    # Route disposal must cancel timers and leave a fresh homepage session.
    click('[data-chat-reset]');page.locator('#demo-input').fill('website')
    page.evaluate('document.querySelector("#demo-form").requestSubmit()')
    click('#primary-nav a[href="platform.html"]');page.wait_for_timeout(500)
    check('Navigation during typing leaves no orphan chat',page.locator('#demo-log').count()==0)
    click('a[href="index.html"]');check('Return to homepage starts a fresh chat',page.locator('.chat-turn').count()==0)
    page.emulate_media(reduced_motion='reduce');page.evaluate('document.documentElement.dataset.motion="off"')
    page.locator('#demo-input').fill('hello')
    page.evaluate('document.querySelector("#demo-input").dispatchEvent(new CompositionEvent("compositionstart", {bubbles:true}));document.querySelector("#demo-form").requestSubmit()')
    check('IME composition does not submit prematurely',page.locator('.chat-turn').count()==0)
    page.evaluate('document.querySelector("#demo-input").dispatchEvent(new CompositionEvent("compositionend", {bubbles:true}))')
    ask('hello');check('Submission works after composition',page.locator('.chat-turn').count()==1)
    click('[data-chat-reset]')
    page.evaluate('''() => {for(let i=0;i<28;i++){document.querySelector('#demo-input').value='hello';document.querySelector('#demo-form').requestSubmit();}}''')
    check('History is capped at 24 turns',page.locator('.chat-turn').count()==24)
    # Validate every topic's browser rendering and internal action hrefs.
    click('[data-chat-reset]')
    topics=page.evaluate('SignalREACHChat.topics.map(t=>({id:t.id,label:t.label}))')
    for topic in topics:
        click('[data-chat-topics-toggle]');page.locator('#demo-topic-search').fill('')
        click('[data-chat-group="All"]');click(f'[data-chat-topic="{topic["id"]}"]')
        check(f'Topic renders: {topic["id"]}',last_title()==topic['label'])
    # Local docs link must route correctly in the self-contained bundle.
    ask('endpoints');click('.chat-turn:last-child a[href="docs.html#endpoint"]')
    expect(page.locator('body')).to_have_attribute('data-page','docs')
    check('Chat action routes to the correct guide','Your endpoint' in page.locator('#docs-article h2').inner_text())
    click('a[href="index.html"]')
    for scheme in ['dark','light']:
        page.evaluate('(scheme)=>document.documentElement.dataset.theme=scheme',scheme)
        for width in [320,390,768,1024,1440]:
            page.set_viewport_size({'width':width,'height':1000})
            for view in ['conversation','topics','example']:
                click('[data-chat-reset]')
                if view=='topics':click('[data-chat-topics-toggle]')
                elif view=='example':page.locator('#demo-mode').select_option('example');ask('responsive')
                size=page.evaluate('({viewport:innerWidth,scrollWidth:document.documentElement.scrollWidth,logHeight:document.querySelector("#demo-log").clientHeight})')
                check(f'{scheme}/{view}: fits {width}px',size['scrollWidth']<=width)
                if view!='topics':check(f'{scheme}/{view}: readable chat area at {width}px',size['logHeight']>=100)
                layouts.append({'theme':scheme,'state':view,**size})
    check('No browser errors',not errors)
    check('No outgoing requests from the offline chat',not requests)
    browser.close()
print(json.dumps({'passed':len(checks),'checks':checks,'layouts':layouts,'pageErrors':errors,'requests':requests},indent=2))
