#!/usr/bin/env python3
"""Build the static website. Python 3.9+, standard library only.
Edit page content here, then run: python tools/build.py
Styles and interactions live in assets/styles.css and assets/app.js.
"""
from pathlib import Path
import html

ROOT = Path(__file__).resolve().parents[1]
REPO = 'https://github.com/falabellamichael/SignalR.E.A.C.H'
ICONS = {
'reset':'<path d="M3 10a9 9 0 1 1 2 8"/><path d="M3 4v6h6"/>',
'arrow':'<path d="M5 12h14M13 6l6 6-6 6"/>',
'arrowup':'<path d="M12 19V5M6 11l6-6 6 6"/>',
'external':'<path d="M14 4h6v6M20 4l-9 9"/><path d="M10 4H5a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-5"/>',
'chevron':'<path d="m9 5 7 7-7 7"/>',
'chevrondown':'<path d="m6 9 6 6 6-6"/>',
'check':'<path d="m5 12 4 4L19 6"/>',
'plus':'<path d="M12 5v14M5 12h14"/>',
'close':'<path d="m6 6 12 12M6 18 18 6"/>',
'copy':'<rect x="8" y="8" width="12" height="12" rx="2"/><path d="M15 8V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h3"/>',
'search':'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 4 4"/>',
'sun':'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2M4.9 4.9l1.4 1.4m11.4 11.4 1.4 1.4M19.1 4.9l-1.4 1.4M6.3 17.7l-1.4 1.4"/>',
'moon':'<path d="M20.8 13.2A9 9 0 0 1 10.8 3.1a9 9 0 1 0 10 10.1Z"/>',
'menu':'<path d="M4 6h16M4 12h16M4 18h16"/>',
'play':'<path d="m9 5 11 7-11 7Z"/>',
'pause':'<path d="M8 5v14M16 5v14"/>',
'code':'<path d="m8 6-6 6 6 6m8-12 6 6-6 6m-3-15-2 18"/>',
'desktop':'<rect x="3" y="3" width="18" height="13" rx="2"/><path d="M8 21h8M12 16v5"/>',
'window':'<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 9h18M7 6.5h.01M10 6.5h.01"/>',
'grid':'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',
'network':'<circle cx="12" cy="5" r="3"/><circle cx="5" cy="18" r="3"/><circle cx="19" cy="18" r="3"/><path d="m10.5 7.5-4 8m7-8 4 8M8 18h8"/>',
'folder':'<path d="M3 7V5a1 1 0 0 1 1-1h5l2 3h9a1 1 0 0 1 1 1v11a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V7Z"/>',
'file':'<path d="M14 2H5a1 1 0 0 0-1 1v18a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1V8Z"/><path d="M14 2v6h6M8 13h8M8 17h6"/>',
'chat':'<path d="M21 11.5a8.5 8.5 0 0 1-8.5 8.5H5l-3 2V11.5a9.5 9.5 0 0 1 19 0Z"/><path d="M7 9h9M7 13h6"/>',
'send':'<path d="m4 4 17 8-17 8 3-8-3-8ZM7 12h14"/>',
'bolt':'<path d="m13 2-9 12h7l-1 8 10-13h-8l1-7Z"/>',
'shield':'<path d="m12 2 8 3v6c0 5-4 9-8 11-4-2-8-6-8-11V5Z"/><path d="m8 12 3 3 5-6"/>',
'key':'<circle cx="8" cy="8" r="5"/><path d="m12 12 9 9m-4-4 3-3m-6 0 3-3"/>',
'git':'<path d="M6 5v12M6 8c0 5 12 1 12 6v3"/><circle cx="6" cy="4" r="2"/><circle cx="6" cy="20" r="2"/><circle cx="18" cy="20" r="2"/>',
'github':'<path d="M9 19c-4.5 1.5-4.5-2.5-6-3m12 6v-3.9a3.3 3.3 0 0 0-.9-2.6c3-.3 6.2-1.5 6.2-7a5.4 5.4 0 0 0-1.5-3.7 5 5 0 0 0-.1-3.7s-1.1-.4-3.8 1.4a12.9 12.9 0 0 0-7 0C5.2.7 4.1 1.1 4.1 1.1A5 5 0 0 0 4 4.8a5.4 5.4 0 0 0-1.5 3.7c0 5.5 3.2 6.7 6.2 7a3.3 3.3 0 0 0-.9 2.6V22"/>',
'chart':'<path d="M4 3v17h17M8 15V9m5 6V5m5 10v-4"/>',
'sliders':'<path d="M3 7h6m6 0h6M3 17h10m6 0h2"/><circle cx="12" cy="7" r="3"/><circle cx="16" cy="17" r="3"/>',
'layers':'<path d="m12 3 10 5-10 5L2 8l10-5Zm-10 9 10 5 10-5M2 16l10 5 10-5"/>',
'globe':'<circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/>',
'book':'<path d="M12 5v15M12 5C8 2 4 3 2 4v15c4-2 7-1 10 1 3-2 6-3 10-1V4c-2-1-6-2-10 1Z"/>',
'info':'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7v.1"/>',
'download':'<path d="M12 3v12m-5-5 5 5 5-5M4 16v4a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-4"/>',
'users':'<circle cx="9" cy="7" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3M16 4a3 3 0 0 1 0 6M17 14a5 5 0 0 1 4 5v2"/>',
'cpu':'<rect x="6" y="6" width="12" height="12" rx="2"/><rect x="9" y="9" width="6" height="6" rx="1"/><path d="M9 2v4m6-4v4M9 18v4m6-4v4M2 9h4m-4 6h4m12-6h4m-4 6h4"/>',
'link':'<path d="m10 13 4-4M8 16l-2 2a4 4 0 0 1-6-6l4-4a4 4 0 0 1 6 0m4-1 2-2a4 4 0 0 1 6 6l-4 4a4 4 0 0 1-6 0" transform="translate(1 0) scale(.92)"/>',
'windows':'<path d="M3 5 11 4v8H3V5Zm10-1 8-1v9h-8V4ZM3 14h8v7l-8-1v-6Zm10 0h8v8l-8-1v-7Z"/>',
'apple':'<path d="M15 3c-1 0-3 1-3 3 2 0 3-1 3-3ZM12 8c-2 0-3-2-6-1-5 2-2 12 1 14 2 1 3-1 5-1s3 2 5 1c2-1 4-5 4-7-4-1-4-5-1-6-3-3-5-1-8 0Z"/>',
'linux':'<path d="M5 8 8 11 5 14m7 1h6"/><rect x="2" y="3" width="20" height="18" rx="3"/>',
'heart':'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>',
'mark':'<path d="m12 3 9 9-9 9-9-9Z"/><circle cx="12" cy="3" r="2" fill="currentColor" stroke="none"/><circle cx="21" cy="12" r="2" fill="currentColor" stroke="none"/><circle cx="12" cy="21" r="2" fill="currentColor" stroke="none"/><circle cx="3" cy="12" r="2" fill="currentColor" stroke="none"/>'
}
def icon(name, extra=''):
    return f'<svg class="icon {extra}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">{ICONS[name]}</svg>'
def brand():
    return f'<a class="brand" href="index.html" aria-label="SignalREACH home"><span class="brand-mark">{icon("mark")}</span><span>Signal<span class="reach">REACH</span></span></a>'
def ext(href, label, classes='text-link'):
    return f'<a class="{classes}" href="{href}" target="_blank" rel="noopener noreferrer">{label}{icon("external")}<span class="sr-only"> (opens in a new tab)</span></a>'
def btn(href,label,secondary=False,ico='arrow'):
    return f'<a class="btn {"btn-secondary" if secondary else "btn-primary"}" href="{href}">{label}{icon(ico)}</a>'
def checks(items):
    return '<ul class="check-list">'+''.join(f'<li>{icon("check")}<span>{x}</span></li>' for x in items)+'</ul>'
def notice(text):
    return f'<div class="notice">{icon("info")}<p>{text}</p></div>'
def small_card(ico,title,desc,link='',label='Explore'):
    action = f'<a class="text-link" href="{link}">{label}{icon("arrow")}</a>' if link else ''
    return f'<article class="small-card reveal">{icon(ico)}<h3>{title}</h3><p>{desc}</p>{action}</article>'

def header(page):
    links=''.join(f'<a href="{p}.html" {"aria-current=page" if page==p else ""}>{label}</a>' for p,label in [('platform','Platform'),('integrations','Integrations'),('docs','Docs'),('about','About')])
    return f'''<a class="skip-link" href="#main">Skip to content</a><div class="scroll-progress" aria-hidden="true"></div>
    <header class="site-header"><div class="container nav-shell">{brand()}<nav class="nav-links" id="primary-nav" aria-label="Main navigation">{links}</nav><div class="nav-actions"><button class="icon-btn theme-toggle" type="button" aria-label="Switch to light theme" title="Switch theme">{icon('moon','theme-moon')}{icon('sun','theme-sun')}</button><span class="nav-divider" aria-hidden="true"></span><a class="btn btn-primary btn-sm" href="download.html">Get started {icon('arrow')}</a><button class="icon-btn menu-toggle" type="button" aria-controls="primary-nav" aria-expanded="false" aria-label="Open navigation">{icon('menu')}</button></div></div></header>'''
def footer():
    return f'''<footer class="site-footer"><div class="container"><div class="footer-top"><div class="footer-brand">{brand()}<p>Your models. Your context.<br>A workspace that brings it all together.</p></div><div class="footer-links"><div><h3>Explore</h3><a href="platform.html">Platform</a><a href="integrations.html">Integrations</a><a href="download.html">Get started</a></div><div><h3>Resources</h3><a href="docs.html">Documentation</a><a href="{REPO}" target="_blank" rel="noopener noreferrer">GitHub ↗</a><a href="{REPO}/issues" target="_blank" rel="noopener noreferrer">Report an issue ↗</a></div><div><h3>SignalREACH</h3><a href="about.html">About the project</a><a href="{REPO}/blob/main/SECURITY.md" target="_blank" rel="noopener noreferrer">Security policy ↗</a><a href="{REPO}/blob/main/LICENSE" target="_blank" rel="noopener noreferrer">MIT license ↗</a></div></div></div><div class="footer-bottom"><span>© 2026 SignalREACH. Built for the way you work.</span><div class="footer-controls"><button class="motion-toggle" type="button" aria-pressed="true">{icon('pause')}<span>Motion on</span></button><a href="#top" class="back-top">Back to top {icon('arrowup')}</a></div></div><div class="footer-watermark" aria-hidden="true">SignalREACH</div></div></footer>'''
def dialogs():
    return f'''<dialog id="tour-dialog" aria-labelledby="tour-title"><div class="dialog-header"><span>THE SIGNALREACH WALKTHROUGH</span><button class="icon-btn" type="button" data-close-dialog aria-label="Close walkthrough">{icon('close')}</button></div><div class="dialog-body" id="tour-body"></div></dialog><dialog id="integration-dialog" aria-labelledby="integration-title"><div class="dialog-header"><span>INTEGRATION DETAILS</span><button class="icon-btn" type="button" data-close-dialog aria-label="Close integration details">{icon('close')}</button></div><div class="dialog-body" id="integration-dialog-body"></div></dialog><div class="toast" role="status" aria-live="polite" aria-atomic="true"></div>'''
def cta(title='Build what comes next.',text='Make room for your next idea. Put it within REACH.',label='Get SignalREACH'):
    return f'<section class="section cta-section"><div class="container"><div class="cta-box reveal"><div><div class="eyebrow">FROM POSSIBILITY TO PROJECT</div><h2>{title}</h2><p>{text}</p></div>{btn("download.html",label)}</div></div></section>'
def page_hero(eyebrow,title,desc,link=''):
    return f'<section class="page-hero {"split" if link else ""}"><div class="container"><div><div class="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{desc}</p></div>{link}</div></section>'
def code_box(text,label='Terminal',cid='code-source'):
    return f'<div class="code-box"><div class="code-toolbar"><span class="mono">{label}</span><button type="button" class="copy-btn" data-copy="{cid}">{icon("copy")}<span>Copy</span></button></div><pre><code id="{cid}">{html.escape(text)}</code></pre></div>'

DEFAULT_CODE = '''curl http://127.0.0.1:20777/v1/chat/completions \\
  -H "Content-Type: application/json" \\
  -H "Authorization: Bearer YOUR_REACH_KEY" \\
  -d '{
    "model": "YOUR_MODEL_ID",
    "messages": [{"role": "user",
      "content": "Let’s build something."}],
    "stream": true
  }' '''.rstrip()

# The preview is illustrative, never connected to a model or actual filesystem.
EDITOR_CODE = '''<span class="ln">1</span><span class="kw">import</span> { useState } <span class="kw">from</span> <span class="str">'react'</span>;
<span class="ln">2</span>
<span class="ln">3</span><span class="comment">// A little context goes a long way.</span>
<span class="ln">4</span><span class="kw">export default function</span> Workspace() {
<span class="ln">5</span>  <span class="kw">const</span> [idea, setIdea] = useState(<span class="str">''</span>);
<span class="ln">6</span>
<span class="ln">7</span>  <span class="kw">return</span> (
<span class="ln">8</span>    &lt;main className=<span class="str">"workspace"</span>&gt;
<span class="ln">9</span>      &lt;h1&gt;Make room for possibility.&lt;/h1&gt;
<span class="ln">10</span>      &lt;Project context={idea} /&gt;
<span class="ln">11</span>    &lt;/main&gt;
<span class="ln">12</span>  );
<span class="ln">13</span>}'''

def preview():
    files=''.join(f'<button class="file-btn {"active" if i==0 else ""}" type="button" data-file="{name}" aria-pressed="{"true" if i==0 else "false"}">{icon("file")}<span>{name}</span></button>' for i,name in enumerate(['app.tsx','theme.css','README.md']))
    return f'''<div class="preview-topline"><div class="tabs" role="tablist" aria-label="Product preview"><button type="button" role="tab" id="preview-tab-workspace" aria-controls="preview-workspace" aria-selected="true" data-preview="workspace">{icon('code')} Workspace</button><button type="button" role="tab" id="preview-tab-chat" aria-controls="preview-chat" aria-selected="false" tabindex="-1" data-preview="chat">Conversations</button><button type="button" role="tab" id="preview-tab-agents" aria-controls="preview-agents" aria-selected="false" tabindex="-1" data-preview="agents">Agent teams</button></div><span class="preview-caption">INTERACTIVE PREVIEW · SAMPLE CONTENT</span></div>
    <div class="studio-window"><div class="window-bar"><span class="window-dots" aria-hidden="true"><i></i><i></i><i></i></span><span class="window-title">{icon('mark')} REACH Studio <span class="muted">/</span> your-next-idea</span><span class="pill">Demo mode</span></div>
    <div class="window-body" id="preview-workspace" role="tabpanel" aria-labelledby="preview-tab-workspace"><aside class="file-sidebar" aria-label="Example project files"><div class="sidebar-label">Explorer</div><div class="file-folder">{icon('chevrondown')}{icon('folder')} your-next-idea</div>{files}<div class="sidebar-bottom">{icon('git')} main <span class="accent">+3</span></div></aside>
    <div class="editor"><div class="editor-bar"><span class="accent mono">TSX</span><span id="editor-file-name">app.tsx</span><small>Sample file</small></div><div class="code-editor" id="editor-code">{EDITOR_CODE}</div><div class="editor-status">{icon('check')}Your context, right where you need it.</div></div>
    <section class="chat-panel" aria-label="Interactive demonstration chat">
      <div class="chat-header"><span>Ask REACH</span><span class="pill gold"><span class="dot"></span>Local heuristic demo</span></div>
      <div class="chat-toolbar">
        <button type="button" class="chat-tool" data-chat-topics-toggle aria-expanded="false" aria-controls="demo-topic-browser">{icon('grid')}<span>Topics</span></button>
        <label class="sr-only" for="demo-mode">Response style</label><select id="demo-mode" class="chat-mode"><option value="quick">Quick answer</option><option value="steps">Step by step</option><option value="example">Show example</option></select>
        <button type="button" class="chat-tool chat-tool-icon" data-chat-export aria-label="Export demo conversation" title="Export conversation">{icon('download')}</button>
        <button type="button" class="chat-tool chat-tool-icon" data-chat-reset aria-label="Reset demo conversation" title="Reset conversation">{icon('reset')}</button>
      </div>
      <div id="demo-topic-browser" class="chat-topic-browser" hidden aria-label="Browse chat topics">
        <label class="sr-only" for="demo-topic-search">Search chat topics and keywords</label><input id="demo-topic-search" class="chat-topic-search" type="search" placeholder="Find a topic or keyword…" autocomplete="off" maxlength="80">
        <div id="demo-topic-groups" class="chat-topic-groups" role="group" aria-label="Filter topics by category"></div>
        <p id="demo-topic-count" class="chat-topic-count" role="status"></p><div id="demo-topic-list" class="chat-topic-list"></div>
      </div>
      <div class="chat-log" id="demo-log" role="log" aria-live="polite" aria-relevant="additions text" aria-busy="false" aria-label="Demo conversation" tabindex="0"><div class="chat-who"><span class="brand-mark">{icon('mark')}</span>REACH · Local guide</div><p class="chat-message">Ask about setup, models, agent teams, design, or troubleshooting. This is a local, scripted demo, not a live AI connection.</p></div>
      <div id="demo-suggestions" class="chat-suggestions" role="group" aria-label="Suggested questions and follow-ups"></div>
      <form class="demo-form" id="demo-form"><label class="sr-only" for="demo-input">Try a demo prompt; no AI request is sent</label><input id="demo-input" type="text" maxlength="600" placeholder="Ask a question or type /help…" autocomplete="off" aria-describedby="demo-hint" required>
        <div class="composer-actions"><span id="demo-status" role="status">Local demo · No AI requests</span><div class="chat-composer-buttons"><button type="button" class="chat-stop" data-chat-stop hidden aria-label="Stop demo response">Stop</button><button type="submit" data-chat-send aria-label="Show demo response">{icon('send')}</button></div></div>
        <div class="chat-input-meta"><span id="demo-hint">Enter to send · Esc to stop · No secrets</span><span id="demo-length" aria-hidden="true">0 / 600</span></div>
      </form>
    </section></div>
    <div class="window-body" id="preview-chat" role="tabpanel" aria-labelledby="preview-tab-chat" hidden><div class="preview-alt"><div><div class="eyebrow">KEEP THE THREAD</div><h3>A conversation.<br>With your context.</h3><p>Choose a model, bring in your files, and work through ideas without leaving your workspace.</p>{checks(['Model and provider selection','Project-aware conversations','Your next step, one message away'])}<a href="platform.html?view=editor" class="text-link">Explore editor chat {icon('arrow')}</a></div><div class="demo-thread"><div class="chat-user">What should I look at before changing the theme?</div><div class="chat-who"><span class="brand-mark">{icon('mark')}</span>REACH <span class="muted">· Sample response</span></div><p class="chat-message">Start with the shared color tokens. Keep the signature gold, then check text contrast against both charcoal and light surfaces.</p><div class="model-tokens"><span>theme.css</span><span>app.tsx</span></div><p class="chat-message" style="margin-top:18px">Make a small change, preview both themes, and review the diff before applying it.</p></div></div></div>
    <div class="window-body" id="preview-agents" role="tabpanel" aria-labelledby="preview-tab-agents" hidden><div class="preview-alt"><div><div class="eyebrow">MORE PERSPECTIVES</div><h3>Give every agent<br>a clear role.</h3><p>Bring custom personas and collaborating agent teams into REACH Studio. Keep the work connected to your project.</p>{checks(['Custom personas','Collaborating agent teams','Visible activity and budget controls'])}<a href="platform.html" class="text-link">Explore Studio {icon('arrow')}</a></div><div class="agent-team"><div class="agent-node"><span>{icon('layers')}</span><div><h4>Planner</h4><p>Break an idea into clear steps</p></div><span class="pill gold">Example role</span></div><div class="agent-node"><span>{icon('code')}</span><div><h4>Builder</h4><p>Work through the implementation</p></div></div><div class="agent-node"><span>{icon('shield')}</span><div><h4>Reviewer</h4><p>Look at the changes together</p></div></div></div></div></div>
    <div class="window-footer"><span>{icon('git')} main · Sample workspace</span><span><span class="dot"></span>Demo only · No AI endpoint connected</span></div></div><p class="preview-hint">{icon('info')}Explore the tabs and try a prompt. This preview does not send AI requests.</p>'''

def home():
    paths=''.join(f'<path class="route-base" d="{d}"/><path class="route-pulse" style="animation-delay:{i*-2}s" d="{d}"/>' for i,d in enumerate(['M115 110C230 110 190 260 280 260','M454 180C370 180 375 260 280 260','M90 365C220 365 190 260 280 260','M435 425C290 425 375 260 280 260']))
    nodes=''.join(f'<div class="orbit-node n{i}"><span class="node-icon">{icon(ico)}</span><div><b>{label}</b><small>{sub}</small></div></div>' for i,ico,label,sub in [(1,'cpu','Your models','One compatible endpoint'),(2,'folder','Your context','Files, not guesswork'),(3,'users','Your agents','Built to collaborate'),(4,'code','Your workflow','On your terms')])
    strips=''.join(f'<a class="surface-label" href="platform.html?view={key}">{icon(ico)}<span>{label}</span></a>' for key,ico,label in [('studio','desktop','REACH Studio'),('editor','code','VS Code'),('relay','grid','SimpleRAG'),('tray','window','Desktop tray')])
    features=f'''<article class="feature-card large reveal"><div class="feature-icon">{icon('cpu')}</div><h3>Your model. Your call.</h3><p>Connect a compatible endpoint and choose the model that fits the work. Your workspace doesn’t have to be your provider.</p><div class="model-tokens"><span>OpenAI-compatible</span><span>Custom endpoints</span><span>Model selection</span></div></article>
    <article class="feature-card large reveal"><div class="feature-icon">{icon('folder')}</div><div class="context-graphic" aria-hidden="true"><span></span><span></span><span></span></div><h3>Context stays close.</h3><p>Your project files and conversations belong together. Give your next question the context it actually needs.</p><div class="model-tokens"><span>{icon('file')} Project files</span><span>{icon('code')} Editor context</span></div></article>
    <article class="feature-card reveal"><div class="feature-icon">{icon('users')}</div><h3>Think as a team.</h3><p>Work with custom personas and collaborating agents in Studio.</p><div class="mini-label"><span class="dot"></span> Different roles. Shared direction.</div></article>
    <article class="feature-card reveal"><div class="feature-icon">{icon('network')}</div><h3>A familiar endpoint.</h3><p>Connect through an OpenAI-compatible interface with streaming support.</p><div class="mini-label mono">POST /v1/chat/completions</div></article>
    <article class="feature-card reveal"><div class="feature-icon">{icon('chart')}</div><h3>Keep usage in view.</h3><p>Manage Studio budgets and inspect relay usage from your control panel.</p><div class="budget-bars" aria-hidden="true">{''.join(f'<i style="--h:{h}%;--delay:-{i*.3}s"></i>' for i,h in enumerate([45,70,56,85,62,100,76,55,82,65,40,70]))}</div></article>'''
    faq_items=[
      ('What is SignalREACH?','SignalREACH stands for <strong>RAG Endpoint &amp; AI Chat Host</strong>. The project includes REACH Studio, a SimpleRAG control panel and relay, a VS Code extension, and a desktop tray bridge.'),
      ('Can I use my own model or endpoint?','REACH Studio connects to a configured OpenAI-compatible endpoint. Available models, authentication, and usage limits depend on that endpoint and its provider. See the <a href="docs.html#endpoint">endpoint guide</a>.'),
      ('Do I need to leave my editor?','No. The project includes a VS Code extension for chat and coding inside the editor. Studio is a separate workspace for people who prefer a standalone desktop app.'),
      ('Is the project open source?','The repository is available under the MIT license. AI providers, hosted endpoints, and optional services may have their own access requirements and charges; open-source software does not mean unlimited free inference.'),
      ('Is this website connected to my AI account?','No. The interactive previews on this website use sample content, not a live model. They do not read your files or send prompts to a provider. Configure your actual connection inside the installed application.')
    ]
    faq=''.join(f'<details><summary>{q}{icon("plus")}</summary><p>{a}</p></details>' for q,a in faq_items)
    return f'''<section class="hero"><div class="hero-glow" aria-hidden="true"></div><div class="container"><div class="hero-grid"><div class="hero-copy reveal"><div class="hero-label"><span class="dot"></span>THE CONNECTED AI WORKSPACE {icon('arrow')}</div><h1>Your ideas.<span class="accent">Within REACH.</span></h1><p>Bring your models, code, and agents into one connected workspace. From a first question to the next thing you ship.</p><div class="button-row">{btn('download.html','Get SignalREACH')}<button class="btn btn-secondary" type="button" data-open-tour>{icon('play')} Take a tour</button></div><div class="hero-note"><span>{icon('github')}Open source</span><span>{icon('desktop')}Windows, macOS &amp; Linux</span></div></div><div class="hero-art reveal" aria-label="SignalREACH connects your models, context, agents and workflow"><span class="art-caption mono" aria-hidden="true">EVERYTHING. CONNECTED.</span><svg class="signal-map" viewBox="0 0 560 520" preserveAspectRatio="none" aria-hidden="true"><circle class="grid-ring" cx="280" cy="260" r="92"/><circle class="grid-ring" cx="280" cy="260" r="150"/><circle class="grid-ring" cx="280" cy="260" r="214"/><circle class="orbit-rim" cx="280" cy="260" r="179"/>{paths}<circle cx="280" cy="46" r="3" fill="var(--gold)" opacity=".45"/><circle cx="280" cy="474" r="2" fill="var(--gold)" opacity=".5"/></svg><div class="orbit-center">{icon('mark')}<span>REACH</span></div>{nodes}<span class="orbit-coordinate mono" aria-hidden="true">01 / A WORKSPACE WITHOUT THE WALLS</span></div></div><div class="hero-bottom"><span class="index">01 — CONNECTED BY DESIGN</span><span class="rule"></span><span>YOUR NEXT CHAPTER STARTS HERE</span>{icon('arrowup')}</div></div></section>
    <div class="surface-strip"><div class="container strip-inner"><span class="strip-label">ONE ECOSYSTEM.<br>YOUR WAY TO WORK.</span>{strips}</div></div>
    <section class="section preview-section" id="workspace"><div class="container"><div class="section-head reveal"><div><div class="eyebrow">MEET YOUR NEW WORKSPACE</div><h2>Everything in context.<br>Nothing in your way.</h2></div><p>Your project on one side. Possibility on the other. Bring the work and the conversation together.</p></div><div class="reveal">{preview()}</div></div></section>
    <section class="section section-line" id="features"><div class="container"><div class="section-head reveal"><div><div class="eyebrow">BUILT AROUND YOUR WORK</div><h2>Less switching.<br><span class="accent">More building.</span></h2></div><a class="text-link" href="platform.html">Explore the platform {icon('arrow')}</a></div><div class="bento">{features}</div></div></section>
    <section class="section section-line" id="workflow"><div class="container workflow"><div class="reveal"><div class="eyebrow">A CLEAR PATH FORWARD</div><h2>From “what if”<br>to what’s next.</h2><div class="workflow-steps" role="tablist" aria-label="Workflow steps" aria-orientation="vertical"><button type="button" class="workflow-step" role="tab" id="step-connect" aria-selected="true" aria-controls="workflow-panel" data-step="connect"><span class="step-n">01</span><span><span class="step-title">Connect your intelligence.</span><span class="step-description">Add your endpoint, choose your model, and make it your own.</span></span></button><button type="button" class="workflow-step" role="tab" id="step-context" aria-selected="false" aria-controls="workflow-panel" tabindex="-1" data-step="context"><span class="step-n">02</span><span><span class="step-title">Bring the right context.</span><span class="step-description">Open a project and keep the relevant files within reach.</span></span></button><button type="button" class="workflow-step" role="tab" id="step-build" aria-selected="false" aria-controls="workflow-panel" tabindex="-1" data-step="build"><span class="step-n">03</span><span><span class="step-title">Build, review, repeat.</span><span class="step-description">Work through an idea with your assistant or an agent team.</span></span></button></div></div><div class="workflow-visual reveal" id="workflow-panel" role="tabpanel" aria-labelledby="step-connect"><div class="panel-label">YOUR CONNECTION <span class="mono">01 / 03</span></div><div class="visual-field"><span class="visual-label">CONNECTION NAME</span><code>My REACH workspace</code></div><div class="visual-field"><span class="visual-label">COMPATIBLE ENDPOINT</span><code>http://127.0.0.1:20777/v1</code></div><div class="visual-field"><span class="visual-label">ACCESS KEY</span><code>••••••••••••••••</code><span class="ok">{icon('key')}</span></div><a class="btn btn-primary" href="docs.html#endpoint">Read the connection guide {icon('arrow')}</a><div class="visual-bottom">{icon('info')}Illustrative settings, not a live connection.</div></div></div></section>
    <section class="section developer-section"><div class="container developer-grid"><div class="reveal"><div class="eyebrow">SPEAKS YOUR LANGUAGE</div><h2>Your stack.<br>Already invited.</h2><p>A familiar interface means less glue code. Point a compatible client at your REACH endpoint and keep building.</p>{checks(['OpenAI-compatible request format','Server-sent event streaming','Host-managed API access'])}<a href="docs.html#endpoint" class="text-link">Read the endpoint guide {icon('arrow')}</a></div><div class="reveal"><div class="code-box"><div class="code-toolbar"><div class="tabs" role="tablist" aria-label="Example language"><button type="button" role="tab" id="lang-curl" aria-controls="api-example-panel" aria-selected="true" data-language="curl">cURL</button><button type="button" role="tab" id="lang-python" aria-controls="api-example-panel" aria-selected="false" tabindex="-1" data-language="python">Python</button><button type="button" role="tab" id="lang-javascript" aria-controls="api-example-panel" aria-selected="false" tabindex="-1" data-language="javascript">JavaScript</button></div><button class="copy-btn" type="button" data-copy="api-example">{icon('copy')}<span>Copy</span></button></div><pre id="api-example-panel" role="tabpanel" aria-labelledby="lang-curl"><code id="api-example">{html.escape(DEFAULT_CODE)}</code></pre><div class="code-foot"><span class="dot"></span>YOUR ENDPOINT. YOUR ACCESS. YOUR MODEL.</div></div><p class="code-disclaimer">Example only. Replace the endpoint, key, and model with your own configuration.</p></div></div></section>
    <section class="section"><div class="container faq-grid"><div class="faq-intro reveal"><div class="eyebrow">A LITTLE MORE CLARITY</div><h2>Good questions.<br>Clear answers.</h2><p>The essentials before you start your next project.</p><a href="docs.html" class="text-link">Go a little deeper {icon('arrow')}</a></div><div class="faq-list reveal">{faq}</div></div></section>{cta()}'''

def platform():
    tab=''.join(f'<button type="button" role="tab" id="platform-{key}" aria-controls="platform-stage" aria-selected="{"true" if key=="studio" else "false"}" {"tabindex=-1" if key!="studio" else ""} data-platform="{key}">{icon(ico)}{label}</button>' for key,ico,label in [('studio','desktop','REACH Studio'),('relay','network','Relay & panel'),('editor','code','VS Code'),('tray','window','Desktop tray')])
    return page_hero('THE PLATFORM','One ecosystem.<br><span class="accent">Four ways to work.</span>','A standalone workspace, an editor companion, a host control panel, or a desktop bridge. Start where you already feel at home.')+f'''<section class="compact-section"><div class="container"><div class="platform-tabs"><div class="tabs" role="tablist" aria-label="Explore a product">{tab}</div></div><div class="platform-stage" id="platform-stage" role="tabpanel" aria-labelledby="platform-studio"><div><span class="pill gold">STANDALONE WORKSPACE</span><h2>REACH Studio</h2><p>Your project, AI conversations, custom personas, and collaborating agent teams in a standalone desktop app.</p>{checks(['Project files and editing','Custom personas and agent teams','Connection and budget controls'])}<a class="text-link" href="docs.html#studio">Open the Studio guide {icon('arrow')}</a></div><div class="platform-graphic"><div class="graphic-title">{icon('mark')} YOUR WORKSPACE, CONNECTED</div><div class="graphic-row highlight">Project workspace <span>Files + editor</span></div><div class="graphic-row">Conversation <span>Your selected model</span></div><div class="graphic-row">Agent teams <span>Custom personas</span></div><div class="graphic-row">Activity &amp; budgets <span>Keep work in view</span></div><div class="visual-bottom">{icon('info')}Feature map · not a live application</div></div></div><div class="capability-grid">{small_card('cpu','Provider flexibility','Choose a configured OpenAI-compatible endpoint. Model availability and limits belong to your provider.')}{small_card('folder','Project context','Keep files and conversations close instead of re-explaining your work in a disconnected chat.')}{small_card('sliders','Explicit control','Configure tools, review behavior, and usage settings in the surface that fits your workflow.')}</div>{notice('Capabilities differ between surfaces. The product tabs describe each surface separately; this website is not the actual control panel.')}</div></section>'''+cta('Find your starting point.','Pick a surface. Bring a project. Make it yours.')

INTEGRATIONS = [
('compatible','OpenAI-compatible API','Endpoints','<>','Use a familiar API format with your configured REACH or compatible endpoint.','Configure the base URL, access key if required, and a model exposed by your host. The website does not test or connect to endpoints.','docs.html#endpoint'),
('vscode','VS Code','Editors','⌘','Keep chat and coding alongside your project files in the REACH extension.','The repository includes the VS Code extension source and setup guide. Use the documented installation path for your environment.','docs.html#editor'),
('simplerag','SimpleRAG','Workspaces','S','Host and manage the relay through the integrated REACH control panel.','The SimpleRAG plugin adds Dashboard, Browser, Endpoint, Models, Usage, Logs, Settings, and About pages. Follow the project README for setup.',REPO+'#readme'),
('studio','REACH Studio','Workspaces','R','A standalone home for files, conversations, personas, and agent teams.','Run Studio on macOS, Windows, or Linux. Configure a compatible endpoint inside Settings → Connection & default model.','docs.html#studio'),
('chatgpt','ChatGPT bridge','Bridges','C','A provider option in the existing REACH desktop tray and editor UI.','Requires the corresponding signed-in provider session and local bridge configuration. Provider terms, access requirements, and limits apply.',REPO+'#desktop-tray-macos-windows-and-linux'),
('copilot','Microsoft 365 Copilot','Bridges','M','Connect through the Copilot option in the local desktop bridge.','Requires the matching provider account and session. Follow the project’s tray setup guide; this is not a Microsoft endorsement.',REPO+'#desktop-tray-macos-windows-and-linux'),
('gemini','Gemini web','Bridges','G','A web-provider route available through the project’s local bridge UI.','Requires an eligible provider session and the local bridge. Availability and usage are governed by the provider.',REPO+'#desktop-tray-macos-windows-and-linux'),
('codegpt','CodeGPT','Bridges','{ }','The existing UI includes a CodeGPT economy-model provider option.','This route depends on the host’s CodeGPT setup and available model catalog. Provider subscriptions and model access rules still apply.',REPO+'#codegpt-economy-models'),
('relay','REACH relay','Endpoints','↗','Connect compatible clients to the endpoint managed by your host.','Host-managed API keys and the configured model catalog determine access. Use the local or hosted URL supplied by the operator.','docs.html#endpoint')
]
def integrations():
    filters=''.join(f'<button type="button" class="filter-btn {"active" if name=="All" else ""}" aria-pressed="{"true" if name=="All" else "false"}" data-filter="{name.lower()}">{name}</button>' for name in ['All','Endpoints','Editors','Workspaces','Bridges'])
    cards=''.join(f'<article class="integration-card reveal" data-category="{cat.lower()}" data-search="{html.escape((name+" "+desc).lower(),quote=True)}"><div class="integration-head"><span class="integration-monogram" aria-hidden="true">{html.escape(mark)}</span><span class="pill">{cat}</span></div><h3>{name}</h3><p>{desc}</p><button type="button" class="text-link" data-integration="{key}" aria-haspopup="dialog">Connection details {icon("arrow")}<span class="sr-only"> for {name}</span></button></article>' for key,name,cat,mark,desc,detail,href in INTEGRATIONS)
    return page_hero('YOUR TOOLS, CONNECTED','Keep your tools.<br><span class="accent">Connect your workflow.</span>','Explore the endpoints, workspaces, and bridge options reflected in the current SignalREACH project.')+f'''<section class="compact-section"><div class="container"><div class="tools-bar"><div class="filter-buttons" role="group" aria-label="Filter integrations">{filters}</div><label class="search-box">{icon('search')}<span class="sr-only">Search integrations</span><input type="search" id="integration-search" placeholder="Find an integration…" autocomplete="off"></label></div><div class="integration-grid" id="integration-grid">{cards}<div class="empty-state" id="integration-empty" hidden><h3>No matching integrations.</h3><p>Try another search or clear the current filter.</p><button class="btn btn-secondary btn-sm" id="clear-integrations" style="margin-top:18px" type="button">Clear filters</button></div></div><p class="search-count" id="integration-count" role="status" aria-live="polite">Showing 9 integrations</p>{notice('Third-party names identify compatibility or existing provider options, not partnerships or endorsements. Some routes require a provider subscription, signed-in session, or host permission.')}</div></section>'''+cta('Bring your own possibilities.','Connect a compatible endpoint and start from there.')

STUDIO_COMMANDS=f'''git clone {REPO}.git
cd SignalR.E.A.C.H/studio
npm ci
npm start'''

def docs():
    nav=''.join(f'<a href="#{key}" data-doc="{key}" class="{"active" if key=="quickstart" else ""}" {"aria-current=page" if key=="quickstart" else ""}>{icon(ico)}{label}</a>' for key,ico,label in [('quickstart','bolt','Quick start'),('studio','desktop','REACH Studio'),('endpoint','network','Connect an endpoint'),('editor','code','VS Code extension'),('security','shield','Privacy & security'),('troubleshooting','sliders','Troubleshooting')])
    article=f'''<div class="doc-meta"><span class="pill gold">START HERE</span><span>Run from source</span></div><h2>Your first REACH workspace.</h2><p>Start with REACH Studio, then connect it to your chosen endpoint. The steps below follow the current Studio guide in the project repository.</p>{notice('<strong>Before you start:</strong> install Git and Node.js 24 LTS for the Studio application. You will also need an accessible OpenAI-compatible endpoint and any credentials required by its host.')}<div class="doc-step"><span>1</span><h3>Get the project and start Studio.</h3></div><p>Run these commands in your terminal. Review the repository and dependencies before installing.</p>{code_box(STUDIO_COMMANDS,'Terminal','quickstart-command')}<div class="doc-step"><span>2</span><h3>Connect your model.</h3></div><p>In Studio, open <strong>Settings → Connection &amp; default model</strong>. Enter your endpoint, access key if needed, and default model. Your host determines which models are available.</p><div class="doc-step"><span>3</span><h3>Open a project.</h3></div><p>Choose <strong>Open Folder</strong> for an existing project, or <strong>New Project → General project</strong> to start with an empty folder. Then start a conversation with the context you need.</p><div class="docs-pager">{ext(REPO+'/blob/main/studio/README.md','Full Studio guide')}<a class="text-link" href="#endpoint" data-doc="endpoint">Connect an endpoint {icon('arrow')}</a></div>'''
    return page_hero('DOCUMENTATION','A clear place to <span class="accent">start.</span>','Practical setup notes. Copyable examples. A direct path to the project’s source documentation.')+f'''<section class="compact-section"><div class="container docs-layout"><aside class="docs-sidebar"><label class="search-box">{icon('search')}<span class="sr-only">Search documentation</span><input type="search" id="docs-search" placeholder="Search the guides…" autocomplete="off"></label><h2>GETTING STARTED</h2><nav class="docs-nav" aria-label="Documentation">{nav}</nav>{ext(REPO+'/tree/main/docs','Source documentation','text-link docs-external')}</aside><article class="docs-article" id="docs-article" tabindex="-1">{article}</article></div></section>'''

def about():
    acronym=''.join(f'<div class="acronym-row"><b>{char}</b><span>{meaning}</span></div>' for char,meaning in [('R','RAG'),('E','Endpoint'),('A','AI'),('C','Chat'),('H','Host')])
    return page_hero('ABOUT SIGNALREACH','Good tools should<br><span class="accent">bring things together.</span>','SignalREACH is an independent, open-source project built around a simple idea: your models, your context, and your work should connect.')+f'''<section class="compact-section"><div class="container"><div class="about-grid"><div class="reveal"><div class="eyebrow">THE IDEA BEHIND THE NAME</div><h2>A shorter distance<br>between idea and action.</h2><p>REACH stands for RAG Endpoint &amp; AI Chat Host. The project brings together a relay, a control panel, an editor extension, a desktop bridge, and a standalone agent workspace.</p><p>Different surfaces. A shared purpose: make AI part of the work, rather than another place to move it.</p>{ext(REPO,'Explore the source')}</div><div class="acronym reveal" aria-label="REACH means RAG Endpoint and AI Chat Host">{acronym}</div></div><div class="about-values"><h2 class="section-subtitle">A few things worth building around.</h2><div class="capability-grid">{small_card('code','Open by design','Read the source, inspect the implementation, and contribute under the repository’s MIT license.')}{small_card('sliders','Choice stays with you','Configure an endpoint and model that fit your needs. Keep provider access, permissions, and budgets explicit.')}{small_card('layers','Built around real work','Projects, context, conversations, and agent teams are more useful when they share a workspace.')}</div></div><div class="creator-bar"><span class="creator-avatar" aria-hidden="true">MA</span><div><b>Brought to you by: SimpleRAG Developers</b><p>Independent project · Open-source repository</p></div>{ext(REPO,'Follow the project')}</div>{notice('This website is a separate presentation layer. Product capabilities are described from the existing repository; interactive examples use sample content, not live model output.')}</div></section>'''+cta('Make something that matters.','Start with an idea. Keep it within REACH.')

def download():
    ostabs=''.join(f'<button type="button" role="tab" id="os-{key}" aria-controls="os-panel" aria-selected="{"true" if key=="windows" else "false"}" {"tabindex=-1" if key!="windows" else ""} data-os="{key}">{icon(ico)}{label}</button>' for key,ico,label in [('windows','windows','Windows'),('macos','apple','macOS'),('linux','linux','Linux')])
    return page_hero('MAKE IT YOUR WORKSPACE','Your next idea<br><span class="accent">starts here.</span>','Choose your environment and follow the source setup guide. No account or API key is collected on this website.')+f'''<section class="compact-section"><div class="container"><div class="download-grid"><div class="download-main reveal"><span class="pill gold">REACH STUDIO</span><h2>A workspace of your own.</h2><p>Project files, AI conversations, personas, and agent teams in one standalone desktop app.</p><div class="os-tabs" role="tablist" aria-label="Choose operating system">{ostabs}</div><div id="os-panel" role="tabpanel" aria-labelledby="os-windows"><ul class="check-list"><li>{icon('check')}<span>Use the documented Windows source workflow.</span></li><li>{icon('check')}<span>Install Git and Node.js 24 LTS.</span></li><li>{icon('check')}<span>Configure a compatible endpoint inside Studio.</span></li></ul></div><div class="button-row">{btn('docs.html#quickstart','Follow setup guide')}{ext(REPO+'/releases','View releases','text-link')}</div><p class="small-note">Release assets vary. Check GitHub for currently published builds; source setup remains available.</p></div><div class="download-side reveal"><div class="eyebrow">PREFER THE TERMINAL?</div><h3>Start from the source.</h3><p>Run these commands after installing Studio’s prerequisites. This builds the editor bundle and launches the desktop app.</p>{code_box(STUDIO_COMMANDS,'Terminal · macOS / Windows / Linux','download-command')}{ext(REPO+'/blob/main/studio/README.md','Read the complete setup guide')}</div></div><div class="download-other"><h2>Already have a place to work?</h2><div class="capability-grid">{small_card('code','Inside VS Code','Add REACH chat and coding to your existing editor workflow.','docs.html#editor','Extension setup')}{small_card('network','Host an endpoint','Use the SimpleRAG panel and relay to manage access and model routing.','docs.html#endpoint','Endpoint guide')}{small_card('window','On your desktop','Explore the local tray bridge and its configured provider options.','platform.html?view=tray','Explore the tray')}</div></div>{notice('<strong>Software and provider access are separate.</strong> The repository is MIT-licensed. Models, optional services, or hosted endpoints can require their own subscriptions, credentials, and usage fees.')}</div></section>'''

PAGES={
'index':('Your ideas. Within REACH.','Bring your models, code, and agents into one connected workspace. Discover SignalREACH, the open-source AI workspace ecosystem.',home),
'platform':('One ecosystem. Four ways to work.','Explore REACH Studio, the SimpleRAG relay and panel, the VS Code extension, and the desktop tray bridge.',platform),
'integrations':('Your tools, connected.','Explore SignalREACH endpoints, workspaces, and provider bridge options. Filter integrations and review connection requirements.',integrations),
'docs':('Documentation and quick start.','Start REACH Studio from source, configure your endpoint, and find the SignalREACH setup and security guides.',docs),
'about':('Built to bring things together.','Learn about SignalREACH, the independent open-source RAG Endpoint and AI Chat Host project.',about),
'download':('Get started with SignalREACH.','Choose your environment, view source setup commands, and find current SignalREACH releases and guides.',download)
}

def build():
    for name,(title,description,render) in PAGES.items():
        chat_scripts = '<script src="assets/chat-engine.js" defer></script><script src="assets/chat-ui.js" defer></script>' if name == 'index' else ''
        doc=f'''<!DOCTYPE html>
<html lang="en" data-theme="dark" data-motion="on">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="{html.escape(description,quote=True)}"><meta name="theme-color" content="#161618"><meta name="color-scheme" content="dark light"><meta property="og:type" content="website"><meta property="og:title" content="SignalREACH — {html.escape(title,quote=True)}"><meta property="og:description" content="{html.escape(description,quote=True)}"><title>{html.escape(title)} | SignalREACH</title><link rel="icon" type="image/svg+xml" href="assets/favicon.svg"><script src="assets/theme.js"></script><link rel="stylesheet" href="assets/styles.css"><script src="assets/data.js" defer></script>{chat_scripts}<script src="assets/app.js" defer></script></head>
<body id="top" data-page="{name}" class="{"home-page" if name=="index" else "subpage"}">{header(name)}<main id="main">{render()}</main>{footer()}{dialogs()}<noscript><div class="notice"><p>The site content and links work without JavaScript. Enable JavaScript to use theme switching, interactive previews, search, and dynamic guide panels.</p></div></noscript></body></html>'''
        (ROOT/f'{name}.html').write_text(doc,encoding='utf-8')
    # Trusted local integration data; separate from user-entered search text.
    import json
    (ROOT/'assets'/'integration-data.json').write_text(json.dumps([dict(id=k,name=n,category=c,mark=m,description=d,detail=t,href=h) for k,n,c,m,d,t,h in INTEGRATIONS],ensure_ascii=False,indent=2),encoding='utf-8')
    (ROOT/'assets'/'data.js').write_text('window.REACH_DATA = '+json.dumps({'icons':ICONS,'integrations':[dict(id=k,name=n,category=c,mark=m,description=d,detail=t,href=h) for k,n,c,m,d,t,h in INTEGRATIONS],'curl':DEFAULT_CODE,'studioCommands':STUDIO_COMMANDS},ensure_ascii=False)+';\n',encoding='utf-8')
    print('Built '+', '.join(f'{name}.html' for name in PAGES))

if __name__=='__main__':
    build()
