/* Reach Studio — language catalog for the message Translate action.
 *
 * GENERATED by scripts/build-languages.cjs from the runtime ICU data via
 * Intl.DisplayNames: every name is the CLDR name for that language and every
 * native form is what the language calls itself. That keeps the catalog in step
 * with the engine instead of vendoring a third-party dataset.
 *
 * 292 languages (the ISO 639-1 set plus the widely used 3-letter and
 * regional codes). Re-run the script after an ICU upgrade to refresh names.
 * Do not hand-edit.
 */
(function expose(factory) {
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  if (typeof window !== 'undefined') window.ReachLanguages = api;
})(function buildLanguages() {
  // [bcp47, English name, native name]
  const ROWS = [
  ['ab', 'Abkhazian', 'Abkhazian'],
  ['aa', 'Afar', 'Afar'],
  ['af', 'Afrikaans', 'Afrikaans'],
  ['ak', 'Akan', 'Akan'],
  ['tw', 'Akan', 'Akan'],
  ['sq', 'Albanian', 'shqip'],
  ['am', 'Amharic', 'አማርኛ'],
  ['ar', 'Arabic', 'العربية'],
  ['an', 'Aragonese', 'Aragonese'],
  ['hy', 'Armenian', 'հայերեն'],
  ['rup', 'Aromanian', 'Aromanian'],
  ['frp', 'Arpitan', 'Arpitan'],
  ['as', 'Assamese', 'অসমীয়া'],
  ['ast', 'Asturian', 'asturianu'],
  ['av', 'Avaric', 'Avaric'],
  ['ae', 'Avestan', 'Avestan'],
  ['awa', 'Awadhi', 'Awadhi'],
  ['ay', 'Aymara', 'Aymara'],
  ['az', 'Azerbaijani', 'azərbaycan'],
  ['bm', 'Bambara', 'bamanakan'],
  ['bn', 'Bangla', 'বাংলা'],
  ['ba', 'Bashkir', 'башҡорт'],
  ['eu', 'Basque', 'euskara'],
  ['bar', 'Bavarian', 'Bavarian'],
  ['be', 'Belarusian', 'беларуская'],
  ['bh', 'Bhojpuri', 'Bhojpuri'],
  ['bho', 'Bhojpuri', 'भोजपुरी'],
  ['bik', 'Bikol', 'Bikol'],
  ['bi', 'Bislama', 'Bislama'],
  ['brx', 'Bodo', 'बर’'],
  ['bs', 'Bosnian', 'bosanski'],
  ['pt-BR', 'Brazilian Portuguese', 'português (Brasil)'],
  ['br', 'Breton', 'brezhoneg'],
  ['en-GB', 'British English', 'British English'],
  ['bg', 'Bulgarian', 'български'],
  ['my', 'Burmese', 'မြန်မာ'],
  ['yue', 'Cantonese', '粵語'],
  ['ca', 'Catalan', 'català'],
  ['ceb', 'Cebuano', 'Cebuano'],
  ['tzm', 'Central Atlas Tamazight', 'Tamaziɣt n laṭlaṣ'],
  ['shu', 'Chadian Arabic', 'Chadian Arabic'],
  ['ch', 'Chamorro', 'Chamorro'],
  ['ce', 'Chechen', 'нохчийн'],
  ['chr', 'Cherokee', 'ᏣᎳᎩ'],
  ['zh', 'Chinese', '中文'],
  ['cho', 'Choctaw', 'Choctaw'],
  ['cu', 'Church Slavic', 'Church Slavic'],
  ['cv', 'Chuvash', 'чӑваш чӗлхи'],
  ['ksh', 'Colognian', 'Kölsch'],
  ['kw', 'Cornish', 'kernewek'],
  ['co', 'Corsican', 'Corsican'],
  ['cr', 'Cree', 'Cree'],
  ['hr', 'Croatian', 'hrvatski'],
  ['cs', 'Czech', 'čeština'],
  ['dak', 'Dakota', 'Dakota'],
  ['da', 'Danish', 'dansk'],
  ['dv', 'Divehi', 'Divehi'],
  ['doi', 'Dogri', 'डोगरी'],
  ['nl', 'Dutch', 'Nederlands'],
  ['dz', 'Dzongkha', 'རྫོང་ཁ'],
  ['frs', 'Eastern Frisian', 'Eastern Frisian'],
  ['arz', 'Egyptian Arabic', 'Egyptian Arabic'],
  ['egl', 'Emilian', 'Emilian'],
  ['en', 'English', 'English'],
  ['eo', 'Esperanto', 'Esperanto'],
  ['et', 'Estonian', 'eesti'],
  ['pt-PT', 'European Portuguese', 'português europeu'],
  ['ee', 'Ewe', 'eʋegbe'],
  ['ext', 'Extremaduran', 'Extremaduran'],
  ['fo', 'Faroese', 'føroyskt'],
  ['fj', 'Fijian', 'Fijian'],
  ['tl', 'Filipino', 'Filipino'],
  ['fil', 'Filipino', 'Filipino'],
  ['fi', 'Finnish', 'suomi'],
  ['fr', 'French', 'français'],
  ['fur', 'Friulian', 'furlan'],
  ['ff', 'Fula', 'Pulaar'],
  ['gl', 'Galician', 'galego'],
  ['gan', 'Gan Chinese', 'Gan Chinese'],
  ['lg', 'Ganda', 'Luganda'],
  ['ka', 'Georgian', 'ქართული'],
  ['de', 'German', 'Deutsch'],
  ['gil', 'Gilbertese', 'Gilbertese'],
  ['el', 'Greek', 'Ελληνικά'],
  ['gn', 'Guarani', 'Guarani'],
  ['gu', 'Gujarati', 'ગુજરાતી'],
  ['ht', 'Haitian Creole', 'Haitian Creole'],
  ['hak', 'Hakka Chinese', 'Hakka Chinese'],
  ['ha', 'Hausa', 'Hausa'],
  ['haw', 'Hawaiian', 'ʻŌlelo Hawaiʻi'],
  ['he', 'Hebrew', 'עברית'],
  ['iw', 'Hebrew', 'עברית'],
  ['hz', 'Herero', 'Herero'],
  ['hi', 'Hindi', 'हिन्दी'],
  ['ho', 'Hiri Motu', 'Hiri Motu'],
  ['hu', 'Hungarian', 'magyar'],
  ['is', 'Icelandic', 'íslenska'],
  ['io', 'Ido', 'Ido'],
  ['ig', 'Igbo', 'Igbo'],
  ['ilo', 'Iloko', 'Iloko'],
  ['id', 'Indonesian', 'Indonesia'],
  ['in', 'Indonesian', 'Indonesia'],
  ['ia', 'Interlingua', 'interlingua'],
  ['ie', 'Interlingue', 'Interlingue'],
  ['iu', 'Inuktitut', 'Inuktitut'],
  ['ik', 'Inupiaq', 'Inupiaq'],
  ['ga', 'Irish', 'Gaeilge'],
  ['it', 'Italian', 'italiano'],
  ['jam', 'Jamaican Creole English', 'Jamaican Creole English'],
  ['ja', 'Japanese', '日本語'],
  ['jv', 'Javanese', 'Jawa'],
  ['jw', 'Javanese', 'Jawa'],
  ['kea', 'Kabuverdianu', 'kabuverdianu'],
  ['kab', 'Kabyle', 'Taqbaylit'],
  ['kl', 'Kalaallisut', 'kalaallisut'],
  ['kn', 'Kannada', 'ಕನ್ನಡ'],
  ['kr', 'Kanuri', 'Kanuri'],
  ['ks', 'Kashmiri', 'کٲشُر'],
  ['csb', 'Kashubian', 'Kashubian'],
  ['kk', 'Kazakh', 'қазақ тілі'],
  ['km', 'Khmer', 'ខ្មែរ'],
  ['ki', 'Kikuyu', 'Gikuyu'],
  ['rw', 'Kinyarwanda', 'Ikinyarwanda'],
  ['tlh', 'Klingon', 'Klingon'],
  ['kv', 'Komi', 'Komi'],
  ['kg', 'Kongo', 'Kongo'],
  ['gom', 'Konkani', 'कोंकणी'],
  ['kok', 'Konkani', 'कोंकणी'],
  ['ko', 'Korean', '한국어'],
  ['kos', 'Kosraean', 'Kosraean'],
  ['avk', 'Kotava', 'Kotava'],
  ['kri', 'Krio', 'Krio'],
  ['kj', 'Kuanyama', 'Kuanyama'],
  ['ku', 'Kurdish', 'kurdî (kurmancî)'],
  ['ky', 'Kyrgyz', 'кыргызча'],
  ['lkt', 'Lakota', 'Lakȟólʼiyapi'],
  ['lo', 'Lao', 'ລາວ'],
  ['la', 'Latin', 'Latin'],
  ['es-419', 'Latin American Spanish', 'español latinoamericano'],
  ['lv', 'Latvian', 'latviešu'],
  ['lij', 'Ligurian', 'ligure'],
  ['li', 'Limburgish', 'Limburgish'],
  ['ln', 'Lingala', 'lingála'],
  ['lfn', 'Lingua Franca Nova', 'Lingua Franca Nova'],
  ['lzh', 'Literary Chinese', 'Literary Chinese'],
  ['lt', 'Lithuanian', 'lietuvių'],
  ['jbo', 'Lojban', 'Lojban'],
  ['lmo', 'Lombard', 'Lombard'],
  ['nds', 'Low German', 'Neddersass’sch'],
  ['sli', 'Lower Silesian', 'Lower Silesian'],
  ['dsb', 'Lower Sorbian', 'dolnoserbšćina'],
  ['lu', 'Luba-Katanga', 'Tshiluba'],
  ['lb', 'Luxembourgish', 'Lëtzebuergesch'],
  ['mk', 'Macedonian', 'македонски'],
  ['mag', 'Magahi', 'Magahi'],
  ['mai', 'Maithili', 'मैथिली'],
  ['mg', 'Malagasy', 'Malagasy'],
  ['ms', 'Malay', 'Melayu'],
  ['ml', 'Malayalam', 'മലയാളം'],
  ['mt', 'Maltese', 'Malti'],
  ['mni', 'Manipuri', 'মৈতৈলোন্'],
  ['gv', 'Manx', 'Gaelg'],
  ['mi', 'Māori', 'Māori'],
  ['mr', 'Marathi', 'मराठी'],
  ['mh', 'Marshallese', 'Marshallese'],
  ['mwr', 'Marwari', 'Marwari'],
  ['nan', 'Min Nan Chinese', 'Min Nan Chinese'],
  ['mwl', 'Mirandese', 'Mirandese'],
  ['moh', 'Mohawk', 'Mohawk'],
  ['mn', 'Mongolian', 'монгол'],
  ['mfe', 'Morisyen', 'kreol morisien'],
  ['ary', 'Moroccan Arabic', 'Moroccan Arabic'],
  ['mus', 'Muscogee', 'Muscogee'],
  ['nqo', 'N’Ko', 'ߒߞߏ'],
  ['na', 'Nauru', 'Nauru'],
  ['nv', 'Navajo', 'Navajo'],
  ['ng', 'Ndonga', 'Ndonga'],
  ['nap', 'Neapolitan', 'Neapolitan'],
  ['ne', 'Nepali', 'नेपाली'],
  ['niu', 'Niuean', 'Niuean'],
  ['nd', 'North Ndebele', 'isiNdebele'],
  ['frr', 'Northern Frisian', 'Northern Frisian'],
  ['se', 'Northern Sami', 'davvisámegiella'],
  ['no', 'Norwegian', 'norsk'],
  ['nb', 'Norwegian Bokmål', 'norsk bokmål'],
  ['nn', 'Norwegian Nynorsk', 'norsk nynorsk'],
  ['nov', 'Novial', 'Novial'],
  ['ny', 'Nyanja', 'Nyanja'],
  ['oc', 'Occitan', 'occitan'],
  ['or', 'Odia', 'ଓଡ଼ିଆ'],
  ['oj', 'Ojibwa', 'Ojibwa'],
  ['om', 'Oromo', 'Oromoo'],
  ['osa', 'Osage', 'Osage'],
  ['os', 'Ossetic', 'ирон'],
  ['pfl', 'Palatine German', 'Palatine German'],
  ['pau', 'Palauan', 'Palauan'],
  ['pi', 'Pali', 'Pali'],
  ['pam', 'Pampanga', 'Pampanga'],
  ['pag', 'Pangasinan', 'Pangasinan'],
  ['pap', 'Papiamento', 'Papiamento'],
  ['ps', 'Pashto', 'پښتو'],
  ['fa', 'Persian', 'فارسی'],
  ['pcd', 'Picard', 'Picard'],
  ['pms', 'Piedmontese', 'piemontèis'],
  ['pon', 'Pohnpeian', 'Pohnpeian'],
  ['pl', 'Polish', 'polski'],
  ['pt', 'Portuguese', 'português'],
  ['pa', 'Punjabi', 'ਪੰਜਾਬੀ'],
  ['qu', 'Quechua', 'Runasimi'],
  ['raj', 'Rajasthani', 'राजस्थानी'],
  ['rif', 'Riffian', 'Riffian'],
  ['rgn', 'Romagnol', 'Romagnol'],
  ['mo', 'Romanian', 'română'],
  ['ro', 'Romanian', 'română'],
  ['rm', 'Romansh', 'rumantsch'],
  ['rn', 'Rundi', 'Ikirundi'],
  ['ru', 'Russian', 'русский'],
  ['sm', 'Samoan', 'Samoan'],
  ['sg', 'Sango', 'Sängö'],
  ['sa', 'Sanskrit', 'संस्कृत भाषा'],
  ['sat', 'Santali', 'ᱥᱟᱱᱛᱟᱲᱤ'],
  ['sc', 'Sardinian', 'sardu'],
  ['sdc', 'Sassarese Sardinian', 'Sassarese Sardinian'],
  ['stq', 'Saterland Frisian', 'Saterland Frisian'],
  ['gd', 'Scottish Gaelic', 'Gàidhlig'],
  ['sr', 'Serbian', 'српски'],
  ['sh', 'Serbian (Latin)', 'srpski (latinica)'],
  ['sr-Latn', 'Serbian (Latin)', 'srpski (latinica)'],
  ['sn', 'Shona', 'chiShona'],
  ['ii', 'Sichuan Yi', 'ꆈꌠꉙ'],
  ['scn', 'Sicilian', 'sicilianu'],
  ['szl', 'Silesian', 'ślōnski'],
  ['zh-Hans', 'Simplified Chinese', '简体中文'],
  ['sd', 'Sindhi', 'سنڌي'],
  ['si', 'Sinhala', 'සිංහල'],
  ['sk', 'Slovak', 'slovenčina'],
  ['sl', 'Slovenian', 'slovenščina'],
  ['so', 'Somali', 'Soomaali'],
  ['nr', 'South Ndebele', 'South Ndebele'],
  ['st', 'Southern Sotho', 'Sesotho'],
  ['es', 'Spanish', 'español'],
  ['srn', 'Sranan Tongo', 'Sranan Tongo'],
  ['zgh', 'Standard Moroccan Tamazight', 'ⵜⴰⵎⴰⵣⵉⵖⵜ'],
  ['su', 'Sundanese', 'Basa Sunda'],
  ['sw', 'Swahili', 'Kiswahili'],
  ['ss', 'Swati', 'Swati'],
  ['sv', 'Swedish', 'svenska'],
  ['gsw', 'Swiss German', 'Schwiizertüütsch'],
  ['shi', 'Tachelhit', 'ⵜⴰⵛⵍⵃⵉⵜ'],
  ['ty', 'Tahitian', 'Tahitian'],
  ['tg', 'Tajik', 'тоҷикӣ'],
  ['ta', 'Tamil', 'தமிழ்'],
  ['tt', 'Tatar', 'татар'],
  ['te', 'Telugu', 'తెలుగు'],
  ['th', 'Thai', 'ไทย'],
  ['bo', 'Tibetan', 'བོད་སྐད་'],
  ['ti', 'Tigrinya', 'ትግርኛ'],
  ['tpi', 'Tok Pisin', 'Tok Pisin'],
  ['tkl', 'Tokelauan', 'Tokelauan'],
  ['to', 'Tongan', 'lea fakatonga'],
  ['zh-Hant', 'Traditional Chinese', '繁體中文'],
  ['ts', 'Tsonga', 'Tsonga'],
  ['tn', 'Tswana', 'Setswana'],
  ['tcy', 'Tulu', 'Tulu'],
  ['aeb', 'Tunisian Arabic', 'Tunisian Arabic'],
  ['tr', 'Turkish', 'Türkçe'],
  ['tk', 'Turkmen', 'türkmen dili'],
  ['uk', 'Ukrainian', 'українська'],
  ['hsb', 'Upper Sorbian', 'hornjoserbšćina'],
  ['ur', 'Urdu', 'اردو'],
  ['ug', 'Uyghur', 'ئۇيغۇرچە'],
  ['uz', 'Uzbek', 'o‘zbek'],
  ['ve', 'Venda', 'Venda'],
  ['vec', 'Venetian', 'veneto'],
  ['vi', 'Vietnamese', 'Tiếng Việt'],
  ['vo', 'Volapük', 'Volapük'],
  ['wa', 'Walloon', 'Walloon'],
  ['war', 'Waray', 'Waray'],
  ['cy', 'Welsh', 'Cymraeg'],
  ['vls', 'West Flemish', 'West Flemish'],
  ['fy', 'Western Frisian', 'Frysk'],
  ['wo', 'Wolof', 'Wolof'],
  ['wuu', 'Wu Chinese', 'Wu Chinese'],
  ['xh', 'Xhosa', 'IsiXhosa'],
  ['hsn', 'Xiang Chinese', 'Xiang Chinese'],
  ['yap', 'Yapese', 'Yapese'],
  ['ji', 'Yiddish', 'ייִדיש'],
  ['yi', 'Yiddish', 'ייִדיש'],
  ['yo', 'Yoruba', 'Èdè Yorùbá'],
  ['zea', 'Zeelandic', 'Zeelandic'],
  ['za', 'Zhuang', 'Vahcuengh'],
  ['zu', 'Zulu', 'isiZulu'],
  ];
  const LANGUAGES = ROWS.map(([code, name, native]) => Object.freeze({ code, name, native }));

  /* Regions, in the order the catalog is grouped. A language's own tag carries
   * no region, so the grouping comes from CLDR's likely-subtags for each primary
   * language plus a small set of explicit spellings for the languages maxim(s)
   * do not cover. Everything else falls through to "Other". */
  const CATEGORIES = Object.freeze([
    'Common', 'Western Europe', 'Eastern Europe', 'Middle East', 'South Asia',
    'East Asia', 'Southeast Asia', 'Central Asia', 'Africa', 'Americas',
    'Pacific', 'Constructed', 'Other',
  ]);

  const WESTERN_EUROPE = new Set(['en', 'fr', 'de', 'es', 'pt', 'it', 'nl', 'ca', 'gl', 'eu', 'ast', 'an', 'oc', 'co', 'sc', 'scn', 'nap', 'lij', 'vec', 'lmo', 'pms', 'fur', 'lad', 'rm', 'gsw', 'bar', 'ksh', 'nds', 'fy', 'li', 'wa', 'pcd', 'sv', 'da', 'nb', 'nn', 'is', 'fo', 'ga', 'gd', 'cy', 'br', 'gv', 'kw', 'el', 'fi', 'et', 'lb', 'mt', 'yi', 'ji', 'sco', 'frr', 'stq', 'vls', 'zea', 'ext', 'mwl', 'egl', 'roa']);
  const EASTERN_EUROPE = new Set(['ru', 'uk', 'be', 'pl', 'cs', 'sk', 'sl', 'hr', 'sr', 'bs', 'mk', 'bg', 'ro', 'hu', 'lt', 'lv', 'sq', 'cu', 'rue', 'szl', 'csb', 'dsb', 'hsb', 'sgs', 'prg', 'sla', 'bat']);
  // All Slavic etymology in the catalog file is covered by the list above.
  const MIDDLE_EAST = new Set(['ar', 'he', 'fa', 'tr', 'ku', 'ckb', 'syr', 'arc', 'sab', 'mzn', 'lrc', 'glk', 'bal', 'ps', 'ur', 'sd', 'az', 'hy', 'ka', 'os', 'kab', 'tzm', 'shi', 'zgh', 'ug', 'dv']);
  const SOUTH_ASIA = new Set(['hi', 'bn', 'pa', 'gu', 'mr', 'ta', 'te', 'kn', 'ml', 'or', 'as', 'mai', 'bho', 'awa', 'hne', 'mag', 'doi', 'sat', 'ks', 'ne', 'si', 'bo', 'dz', 'new', 'gom', 'kok', 'mni', 'raj', 'sa', 'pi']);
  const EAST_ASIA = new Set(['zh', 'ja', 'ko', 'yue', 'wuu', 'hsn', 'nan', 'hak', 'gan', 'cjy', 'cdo', 'mnp', 'lzh', 'vi']);
  const SOUTHEAST_ASIA = new Set(['th', 'lo', 'km', 'my', 'id', 'ms', 'fil', 'tl', 'jv', 'su', 'ceb', 'ilo', 'hil', 'war', 'pam', 'bik', 'bcl', 'krj', 'mad', 'min', 'bug', 'ban', 'ace', 'iba', 'tet', 'mi', 'fj', 'sm', 'to', 'haw']);
  const CENTRAL_ASIA = new Set(['kk', 'ky', 'uz', 'tk', 'tg', 'mn', 'tt', 'ba', 'cv', 'sah', 'krc', 'kbd', 'ce', 'inh', 'av', 'dar', 'lez', 'tab', 'nog', 'xal', 'bua', 'tyv', 'alt', 'kjh']);
  const AFRICA = new Set(['sw', 'am', 'ti', 'om', 'so', 'ha', 'ig', 'yo', 'zu', 'xh', 'af', 'st', 'tn', 'ts', 'ss', 've', 'nso', 'rw', 'rn', 'lg', 'ln', 'mg', 'ny', 'sn', 'wo', 'ff', 'bm', 'ee', 'tw', 'ak', 'lu', 'lua', 'kg', 'sg', 'mos', 'kr', 'knc', 'dyu', 'nd', 'nr', 'umb', 'her', 'naq', 'nyn', 'teo', 'luo', 'kam', 'mer', 'kln', 'saq', 'dav', 'ebu', 'guz', 'ki', 'jmc', 'rof', 'rwk', 'vun', 'asa', 'bez', 'ksb', 'lag', 'sbp', 'seh', 'xog', 'zgh', 'shi', 'kab', 'ber', 'cgg', 'ttj', 'nyo', 'xsm', 'agq', 'bas', 'dua', 'ewo', 'jgo', 'kkj', 'ksf', 'mgo', 'mua', 'nmg', 'nnh', 'yav', 'ybb', 'bax', 'bfd', 'fuv', 'gez', 'wal', 'aa', 'ab', 'ach', 'ada', 'adj', 'agr', 'any', 'bci', 'bem', 'bez', 'bkv', 'bss', 'bum', 'byv', 'cch', 'dje', 'dnn', 'dtp', 'efi', 'eka', 'ekp', 'fan', 'fmp', 'fuv', 'gba', 'gnd', 'guw', 'gya', 'ibo', 'jbu', 'kaj', 'kcg', 'kdv', 'kes', 'khq', 'kia', 'kpe', 'kqn', 'ksh', 'kwu', 'laj', 'lam', 'lek', 'lol', 'maf', 'mas', 'mbo', 'mcu', 'mgh', 'mgy', 'mhi', 'mkw', 'mlg', 'moz', 'mzn', 'nge', 'nnh', 'nso', 'pcm', 'pes', 'pfl', 'poi', 'saf', 'sba', 'sco', 'sid', 'sok', 'srr', 'tiv', 'tum', 'ug', 'umb', 'vai', 'wae', 'yav', 'zad', 'zul']);
  const AMERICAS = new Set(['qu', 'ay', 'gn', 'nah', 'ht', 'jam', 'pap', 'srn', 'gsw', 'iu', 'kl', 'cr', 'oj', 'nav', 'chr', 'moh', 'dak', 'lkt', 'myn', 'quc', 'cak', 'kkj', 'arn', 'aym', 'bzd', 'cab', 'cak', 'crh', 'dav', 'guc', 'hus', 'kea', 'kek', 'kpj', 'mam', 'mfe', 'myn', 'nhn', 'nch', 'poi', 'qug', 'quz', 'sab', 'tzh', 'yua', 'zap']);
  const PACIFIC = new Set(['mi', 'fj', 'sm', 'to', 'haw', 'ty', 'ch', 'gil', 'pau', 'yap', 'kos', 'pon', 'mh', 'na', 'nio', 'niu', 'tvl', 'tkl', 'wls', 'fud', 'mri', 'rap', 'rar', 'tah', 'ton', 'smo', 'mah', 'bik', 'pag', 'ivv', 'itv', 'aup', 'fij']);
  const CONSTRUCTED = new Set(['eo', 'ia', 'ie', 'io', 'jbo', 'tlh', 'vo', 'afh', 'nov', 'lfn', 'qya', 'rmg', 'sjn', 'tok', 'tzl', 'zbl', 'avk', 'la']);

  /* Legacy ISO 639-1 codes CLDR maximises to nothing, plus the region/script
   * variants and a few languages whose maxim kept the main language's region.
   * Without this they all fell into "Other". */
  const EXTRA_REGION = Object.freeze({
    rup: 'Eastern Europe', frp: 'Western Europe', rgn: 'Western Europe', sdc: 'Western Europe',
    sli: 'Eastern Europe', mo: 'Eastern Europe', sh: 'Eastern Europe', 'sr-Latn': 'Eastern Europe',
    kv: 'Eastern Europe', se: 'Western Europe', no: 'Western Europe',
    bh: 'South Asia', brx: 'South Asia', mwr: 'South Asia', tcy: 'South Asia', ii: 'East Asia',
    za: 'East Asia', 'zh-Hans': 'East Asia', 'zh-Hant': 'East Asia',
    bi: 'Pacific', ho: 'Pacific', tpi: 'Pacific',
    jw: 'Southeast Asia', in: 'Southeast Asia',
    iw: 'Middle East', osa: 'Americas', nv: 'Americas', cho: 'Americas', mus: 'Americas',
    ik: 'Americas', nqo: 'Africa', hz: 'Africa', kj: 'Africa', ng: 'Africa', kri: 'Africa',
    arz: 'Middle East', ary: 'Middle East', aeb: 'Middle East', shu: 'Middle East',
    rif: 'Africa', 'pt-BR': 'Americas', 'pt-PT': 'Western Europe', 'en-GB': 'Western Europe',
    ae: 'Middle East', frs: 'Western Europe',
  });
  const CATEGORY_BY_CODE = new Map(Object.entries(EXTRA_REGION));

  const REGIONS = [
    ['Western Europe', WESTERN_EUROPE], ['Eastern Europe', EASTERN_EUROPE],
    ['Middle East', MIDDLE_EAST], ['South Asia', SOUTH_ASIA], ['East Asia', EAST_ASIA],
    ['Southeast Asia', SOUTHEAST_ASIA], ['Central Asia', CENTRAL_ASIA],
    ['Africa', AFRICA], ['Americas', AMERICAS], ['Pacific', PACIFIC],
    ['Constructed', CONSTRUCTED],
  ];

  /* The languages the popover offers first, in the order it offers them. */
  const DEFAULT_TARGETS = Object.freeze(
    ['en', 'es', 'fr', 'de', 'pt', 'it', 'ja', 'zh', 'ko', 'ru', 'ar', 'hi']
      .map(code => LANGUAGES.find(l => l.code === code)).filter(Boolean));

  let likelyCache = null;
  /* Which region a language's speakers are most likely in, via CLDR. */
  function likelyRegion(code) {
    if (likelyCache === null) likelyCache = new Map();
    if (likelyCache.has(code)) return likelyCache.get(code);
    let region = '';
    try {
      const parts = new Intl.Locale(code).maximize().region;
      region = parts || '';
    } catch { region = ''; }
    likelyCache.set(code, region);
    return region;
  }

  /* One flat list, grouped by region, with the most-wanted languages repeated at
   * the top under "Common". `filter` narrows the catalog first, so search and
   * grouping share one code path. */
  function grouped(list, categories = CATEGORIES) {
    const buckets = new Map(categories.map(name => [name, []]));
    const present = new Set(list.map(l => l.code));
    // Common repeats the most-wanted languages in a deliberate order (they are
    // the ones a user reaches for), so it is built from DEFAULT_TARGETS rather
    // than from the catalog's alphabetical scan.
    for (const language of DEFAULT_TARGETS) {
      if (present.has(language.code)) buckets.get('Common').push(language);
    }
    for (const language of list) {
      let region = CATEGORY_BY_CODE.get(language.code) || '';
      for (const [name, codes] of REGIONS) {
        if (codes.has(language.code)) { region = name; break; }
      }
      if (!region) {
        const maximized = likelyRegion(language.code);
        region = REGION_TO_CATEGORY[maximized] || 'Other';
      }
      buckets.get(region).push(language);
    }
    // Alphabetical inside a group keeps a 292-row list scannable. Common keeps
    // the order above, so the most-wanted come first.
    const out = [];
    for (const name of categories) {
      const items = buckets.get(name) || [];
      if (!items.length) continue;
      if (name !== 'Common') items.sort((a, b) => a.name.localeCompare(b.name, 'en'));
      out.push(Object.freeze({ name, items: Object.freeze(items) }));
    }
    return out;
  }

  const REGION_TO_CATEGORY = Object.freeze({
    '021': 'Americas', '029': 'Americas', '013': 'Americas', '005': 'Americas', '419': 'Americas',
    '030': 'East Asia', '034': 'South Asia', '035': 'Southeast Asia', '039': 'Western Europe',
    '143': 'Central Asia', '145': 'Middle East', '151': 'Eastern Europe', '154': 'Western Europe',
    '155': 'Western Europe', '202': 'Africa', '015': 'Africa', '002': 'Africa',
    '053': 'Pacific', '054': 'Pacific', '057': 'Pacific', '009': 'Pacific',
  });

  // Case-insensitive lookup by tag, English name, or native name, so a value
  // saved by an older build still resolves. A colliding name (several languages
  // share one) must resolve to the SAME row every time, or a search result and a
  // later lookup would disagree: keep the first row that claims a key.
  const INDEX = new Map();
  for (const language of LANGUAGES) {
    for (const key of [language.code, language.name, language.native]) {
      INDEX.set(key.toLowerCase(), language);
    }
  }

  function get(code) {
    return (code && INDEX.get(String(code).toLowerCase())) || null;
  }

  function displayName(code, inLocale) {
    const language = get(code);
    if (!language) return code ? String(code) : '';
    try {
      const localized = new Intl.DisplayNames([inLocale || 'en'], { type: 'language' }).of(language.code);
      if (localized && localized.toLowerCase() !== language.code.toLowerCase()) return localized;
    } catch { /* fall through to the catalog name */ }
    return language.name;
  }

  // Languages whose name or native name starts with the query, then contains it.
  // Empty query returns the head of the alphabetical list.
  function search(query, limit = 60) {
    const needle = String(query || '').trim().toLowerCase();
    if (!needle) return LANGUAGES.slice(0, limit);
    /* An exact tag/name hit ranks first, resolved through the index rather than
     * the scan: the scan stops once it has enough rows, so a match later in the
     * alphabet (Spanish for "es", after Esperanto) would never be reached. */
    const hit = INDEX.get(needle);
    const exact = hit ? [hit] : [];
    const starts = [];
    const contains = [];
    for (const language of LANGUAGES) {
      if (language === hit) continue;
      const code = language.code.toLowerCase();
      const name = language.name.toLowerCase();
      const native = language.native.toLowerCase();
      if (name.startsWith(needle) || native.startsWith(needle) || code.startsWith(needle)) starts.push(language);
      else if (name.includes(needle) || native.includes(needle) || code.includes(needle)) contains.push(language);
      if (starts.length + contains.length > limit * 4) break;
    }
    return [...exact, ...starts, ...contains].slice(0, limit);
  }

    return Object.freeze({ LANGUAGES, DEFAULT_TARGETS, CATEGORIES, get, displayName, search, grouped });
});
