/* Reach Studio — language catalog for the message Translate action.
 *
 * GENERATED by scripts/build-languages.cjs from the runtime ICU data via
 * Intl.DisplayNames: every name is the CLDR name for that language and every
 * native form is what the language calls itself. That keeps the catalog in step
 * with the engine instead of vendoring a third-party dataset.
 *
 * 292 languages (the ISO 639-1 set plus the widely used 3-letter and
 * regional codes). Re-run the script after an ICU upgrade to refresh names.
 * Do not hand-edit.
 */
(function expose(factory) {
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  if (typeof window !== 'undefined') window.ReachLanguages = api;
})(function buildLanguages() {
  // [bcp47, English name, native name]
  const ROWS = [
  ['ab', 'Abkhazian', 'Abkhazian'],
  ['aa', 'Afar', 'Afar'],
  ['af', 'Afrikaans', 'Afrikaans'],
  ['ak', 'Akan', 'Akan'],
  ['tw', 'Akan', 'Akan'],
  ['sq', 'Albanian', 'shqip'],
  ['am', 'Amharic', 'አማርኛ'],
  ['ar', 'Arabic', 'العربية'],
  ['an', 'Aragonese', 'Aragonese'],
  ['hy', 'Armenian', 'հայերեն'],
  ['rup', 'Aromanian', 'Aromanian'],
  ['frp', 'Arpitan', 'Arpitan'],
  ['as', 'Assamese', 'অসমীয়া'],
  ['ast', 'Asturian', 'asturianu'],
  ['av', 'Avaric', 'Avaric'],
  ['ae', 'Avestan', 'Avestan'],
  ['awa', 'Awadhi', 'Awadhi'],
  ['ay', 'Aymara', 'Aymara'],
  ['az', 'Azerbaijani', 'azərbaycan'],
  ['bm', 'Bambara', 'bamanakan'],
  ['bn', 'Bangla', 'বাংলা'],
  ['ba', 'Bashkir', 'башҡорт'],
  ['eu', 'Basque', 'euskara'],
  ['bar', 'Bavarian', 'Bavarian'],
  ['be', 'Belarusian', 'беларуская'],
  ['bh', 'Bhojpuri', 'Bhojpuri'],
  ['bho', 'Bhojpuri', 'भोजपुरी'],
  ['bik', 'Bikol', 'Bikol'],
  ['bi', 'Bislama', 'Bislama'],
  ['brx', 'Bodo', 'बर’'],
  ['bs', 'Bosnian', 'bosanski'],
  ['pt-BR', 'Brazilian Portuguese', 'português (Brasil)'],
  ['br', 'Breton', 'brezhoneg'],
  ['en-GB', 'British English', 'British English'],
  ['bg', 'Bulgarian', 'български'],
  ['my', 'Burmese', 'မြန်မာ'],
  ['yue', 'Cantonese', '粵語'],
  ['ca', 'Catalan', 'català'],
  ['ceb', 'Cebuano', 'Cebuano'],
  ['tzm', 'Central Atlas Tamazight', 'Tamaziɣt n laṭlaṣ'],
  ['shu', 'Chadian Arabic', 'Chadian Arabic'],
  ['ch', 'Chamorro', 'Chamorro'],
  ['ce', 'Chechen', 'нохчийн'],
  ['chr', 'Cherokee', 'ᏣᎳᎩ'],
  ['zh', 'Chinese', '中文'],
  ['cho', 'Choctaw', 'Choctaw'],
  ['cu', 'Church Slavic', 'Church Slavic'],
  ['cv', 'Chuvash', 'чӑваш чӗлхи'],
  ['ksh', 'Colognian', 'Kölsch'],
  ['kw', 'Cornish', 'kernewek'],
  ['co', 'Corsican', 'Corsican'],
  ['cr', 'Cree', 'Cree'],
  ['hr', 'Croatian', 'hrvatski'],
  ['cs', 'Czech', 'čeština'],
  ['dak', 'Dakota', 'Dakota'],
  ['da', 'Danish', 'dansk'],
  ['dv', 'Divehi', 'Divehi'],
  ['doi', 'Dogri', 'डोगरी'],
  ['nl', 'Dutch', 'Nederlands'],
  ['dz', 'Dzongkha', 'རྫོང་ཁ'],
  ['frs', 'Eastern Frisian', 'Eastern Frisian'],
  ['arz', 'Egyptian Arabic', 'Egyptian Arabic'],
  ['egl', 'Emilian', 'Emilian'],
  ['en', 'English', 'English'],
  ['eo', 'Esperanto', 'Esperanto'],
  ['et', 'Estonian', 'eesti'],
  ['pt-PT', 'European Portuguese', 'português europeu'],
  ['ee', 'Ewe', 'eʋegbe'],
  ['ext', 'Extremaduran', 'Extremaduran'],
  ['fo', 'Faroese', 'føroyskt'],
  ['fj', 'Fijian', 'Fijian'],
  ['tl', 'Filipino', 'Filipino'],
  ['fil', 'Filipino', 'Filipino'],
  ['fi', 'Finnish', 'suomi'],
  ['fr', 'French', 'français'],
  ['fur', 'Friulian', 'furlan'],
  ['ff', 'Fula', 'Pulaar'],
  ['gl', 'Galician', 'galego'],
  ['gan', 'Gan Chinese', 'Gan Chinese'],
  ['lg', 'Ganda', 'Luganda'],
  ['ka', 'Georgian', 'ქართული'],
  ['de', 'German', 'Deutsch'],
  ['gil', 'Gilbertese', 'Gilbertese'],
  ['el', 'Greek', 'Ελληνικά'],
  ['gn', 'Guarani', 'Guarani'],
  ['gu', 'Gujarati', 'ગુજરાતી'],
  ['ht', 'Haitian Creole', 'Haitian Creole'],
  ['hak', 'Hakka Chinese', 'Hakka Chinese'],
  ['ha', 'Hausa', 'Hausa'],
  ['haw', 'Hawaiian', 'ʻŌlelo Hawaiʻi'],
  ['he', 'Hebrew', 'עברית'],
  ['iw', 'Hebrew', 'עברית'],
  ['hz', 'Herero', 'Herero'],
  ['hi', 'Hindi', 'हिन्दी'],
  ['ho', 'Hiri Motu', 'Hiri Motu'],
  ['hu', 'Hungarian', 'magyar'],
  ['is', 'Icelandic', 'íslenska'],
  ['io', 'Ido', 'Ido'],
  ['ig', 'Igbo', 'Igbo'],
  ['ilo', 'Iloko', 'Iloko'],
  ['id', 'Indonesian', 'Indonesia'],
  ['in', 'Indonesian', 'Indonesia'],
  ['ia', 'Interlingua', 'interlingua'],
  ['ie', 'Interlingue', 'Interlingue'],
  ['iu', 'Inuktitut', 'Inuktitut'],
  ['ik', 'Inupiaq', 'Inupiaq'],
  ['ga', 'Irish', 'Gaeilge'],
  ['it', 'Italian', 'italiano'],
  ['jam', 'Jamaican Creole English', 'Jamaican Creole English'],
  ['ja', 'Japanese', '日本語'],
  ['jv', 'Javanese', 'Jawa'],
  ['jw', 'Javanese', 'Jawa'],
  ['kea', 'Kabuverdianu', 'kabuverdianu'],
  ['kab', 'Kabyle', 'Taqbaylit'],
  ['kl', 'Kalaallisut', 'kalaallisut'],
  ['kn', 'Kannada', 'ಕನ್ನಡ'],
  ['kr', 'Kanuri', 'Kanuri'],
  ['ks', 'Kashmiri', 'کٲشُر'],
  ['csb', 'Kashubian', 'Kashubian'],
  ['kk', 'Kazakh', 'қазақ тілі'],
  ['km', 'Khmer', 'ខ្មែរ'],
  ['ki', 'Kikuyu', 'Gikuyu'],
  ['rw', 'Kinyarwanda', 'Ikinyarwanda'],
  ['tlh', 'Klingon', 'Klingon'],
  ['kv', 'Komi', 'Komi'],
  ['kg', 'Kongo', 'Kongo'],
  ['gom', 'Konkani', 'कोंकणी'],
  ['kok', 'Konkani', 'कोंकणी'],
  ['ko', 'Korean', '한국어'],
  ['kos', 'Kosraean', 'Kosraean'],
  ['avk', 'Kotava', 'Kotava'],
  ['kri', 'Krio', 'Krio'],
  ['kj', 'Kuanyama', 'Kuanyama'],
  ['ku', 'Kurdish', 'kurdî (kurmancî)'],
  ['ky', 'Kyrgyz', 'кыргызча'],
  ['lkt', 'Lakota', 'Lakȟólʼiyapi'],
  ['lo', 'Lao', 'ລາວ'],
  ['la', 'Latin', 'Latin'],
  ['es-419', 'Latin American Spanish', 'español latinoamericano'],
  ['lv', 'Latvian', 'latviešu'],
  ['lij', 'Ligurian', 'ligure'],
  ['li', 'Limburgish', 'Limburgish'],
  ['ln', 'Lingala', 'lingála'],
  ['lfn', 'Lingua Franca Nova', 'Lingua Franca Nova'],
  ['lzh', 'Literary Chinese', 'Literary Chinese'],
  ['lt', 'Lithuanian', 'lietuvių'],
  ['jbo', 'Lojban', 'Lojban'],
  ['lmo', 'Lombard', 'Lombard'],
  ['nds', 'Low German', 'Neddersass’sch'],
  ['sli', 'Lower Silesian', 'Lower Silesian'],
  ['dsb', 'Lower Sorbian', 'dolnoserbšćina'],
  ['lu', 'Luba-Katanga', 'Tshiluba'],
  ['lb', 'Luxembourgish', 'Lëtzebuergesch'],
  ['mk', 'Macedonian', 'македонски'],
  ['mag', 'Magahi', 'Magahi'],
  ['mai', 'Maithili', 'मैथिली'],
  ['mg', 'Malagasy', 'Malagasy'],
  ['ms', 'Malay', 'Melayu'],
  ['ml', 'Malayalam', 'മലയാളം'],
  ['mt', 'Maltese', 'Malti'],
  ['mni', 'Manipuri', 'মৈতৈলোন্'],
  ['gv', 'Manx', 'Gaelg'],
  ['mi', 'Māori', 'Māori'],
  ['mr', 'Marathi', 'मराठी'],
  ['mh', 'Marshallese', 'Marshallese'],
  ['mwr', 'Marwari', 'Marwari'],
  ['nan', 'Min Nan Chinese', 'Min Nan Chinese'],
  ['mwl', 'Mirandese', 'Mirandese'],
  ['moh', 'Mohawk', 'Mohawk'],
  ['mn', 'Mongolian', 'монгол'],
  ['mfe', 'Morisyen', 'kreol morisien'],
  ['ary', 'Moroccan Arabic', 'Moroccan Arabic'],
  ['mus', 'Muscogee', 'Muscogee'],
  ['nqo', 'N’Ko', 'ߒߞߏ'],
  ['na', 'Nauru', 'Nauru'],
  ['nv', 'Navajo', 'Navajo'],
  ['ng', 'Ndonga', 'Ndonga'],
  ['nap', 'Neapolitan', 'Neapolitan'],
  ['ne', 'Nepali', 'नेपाली'],
  ['niu', 'Niuean', 'Niuean'],
  ['nd', 'North Ndebele', 'isiNdebele'],
  ['frr', 'Northern Frisian', 'Northern Frisian'],
  ['se', 'Northern Sami', 'davvisámegiella'],
  ['no', 'Norwegian', 'norsk'],
  ['nb', 'Norwegian Bokmål', 'norsk bokmål'],
  ['nn', 'Norwegian Nynorsk', 'norsk nynorsk'],
  ['nov', 'Novial', 'Novial'],
  ['ny', 'Nyanja', 'Nyanja'],
  ['oc', 'Occitan', 'occitan'],
  ['or', 'Odia', 'ଓଡ଼ିଆ'],
  ['oj', 'Ojibwa', 'Ojibwa'],
  ['om', 'Oromo', 'Oromoo'],
  ['osa', 'Osage', 'Osage'],
  ['os', 'Ossetic', 'ирон'],
  ['pfl', 'Palatine German', 'Palatine German'],
  ['pau', 'Palauan', 'Palauan'],
  ['pi', 'Pali', 'Pali'],
  ['pam', 'Pampanga', 'Pampanga'],
  ['pag', 'Pangasinan', 'Pangasinan'],
  ['pap', 'Papiamento', 'Papiamento'],
  ['ps', 'Pashto', 'پښتو'],
  ['fa', 'Persian', 'فارسی'],
  ['pcd', 'Picard', 'Picard'],
  ['pms', 'Piedmontese', 'piemontèis'],
  ['pon', 'Pohnpeian', 'Pohnpeian'],
  ['pl', 'Polish', 'polski'],
  ['pt', 'Portuguese', 'português'],
  ['pa', 'Punjabi', 'ਪੰਜਾਬੀ'],
  ['qu', 'Quechua', 'Runasimi'],
  ['raj', 'Rajasthani', 'राजस्थानी'],
  ['rif', 'Riffian', 'Riffian'],
  ['rgn', 'Romagnol', 'Romagnol'],
  ['mo', 'Romanian', 'română'],
  ['ro', 'Romanian', 'română'],
  ['rm', 'Romansh', 'rumantsch'],
  ['rn', 'Rundi', 'Ikirundi'],
  ['ru', 'Russian', 'русский'],
  ['sm', 'Samoan', 'Samoan'],
  ['sg', 'Sango', 'Sängö'],
  ['sa', 'Sanskrit', 'संस्कृत भाषा'],
  ['sat', 'Santali', 'ᱥᱟᱱᱛᱟᱲᱤ'],
  ['sc', 'Sardinian', 'sardu'],
  ['sdc', 'Sassarese Sardinian', 'Sassarese Sardinian'],
  ['stq', 'Saterland Frisian', 'Saterland Frisian'],
  ['gd', 'Scottish Gaelic', 'Gàidhlig'],
  ['sr', 'Serbian', 'српски'],
  ['sh', 'Serbian (Latin)', 'srpski (latinica)'],
  ['sr-Latn', 'Serbian (Latin)', 'srpski (latinica)'],
  ['sn', 'Shona', 'chiShona'],
  ['ii', 'Sichuan Yi', 'ꆈꌠꉙ'],
  ['scn', 'Sicilian', 'sicilianu'],
  ['szl', 'Silesian', 'ślōnski'],
  ['zh-Hans', 'Simplified Chinese', '简体中文'],
  ['sd', 'Sindhi', 'سنڌي'],
  ['si', 'Sinhala', 'සිංහල'],
  ['sk', 'Slovak', 'slovenčina'],
  ['sl', 'Slovenian', 'slovenščina'],
  ['so', 'Somali', 'Soomaali'],
  ['nr', 'South Ndebele', 'South Ndebele'],
  ['st', 'Southern Sotho', 'Sesotho'],
  ['es', 'Spanish', 'español'],
  ['srn', 'Sranan Tongo', 'Sranan Tongo'],
  ['zgh', 'Standard Moroccan Tamazight', 'ⵜⴰⵎⴰⵣⵉⵖⵜ'],
  ['su', 'Sundanese', 'Basa Sunda'],
  ['sw', 'Swahili', 'Kiswahili'],
  ['ss', 'Swati', 'Swati'],
  ['sv', 'Swedish', 'svenska'],
  ['gsw', 'Swiss German', 'Schwiizertüütsch'],
  ['shi', 'Tachelhit', 'ⵜⴰⵛⵍⵃⵉⵜ'],
  ['ty', 'Tahitian', 'Tahitian'],
  ['tg', 'Tajik', 'тоҷикӣ'],
  ['ta', 'Tamil', 'தமிழ்'],
  ['tt', 'Tatar', 'татар'],
  ['te', 'Telugu', 'తెలుగు'],
  ['th', 'Thai', 'ไทย'],
  ['bo', 'Tibetan', 'བོད་སྐད་'],
  ['ti', 'Tigrinya', 'ትግርኛ'],
  ['tpi', 'Tok Pisin', 'Tok Pisin'],
  ['tkl', 'Tokelauan', 'Tokelauan'],
  ['to', 'Tongan', 'lea fakatonga'],
  ['zh-Hant', 'Traditional Chinese', '繁體中文'],
  ['ts', 'Tsonga', 'Tsonga'],
  ['tn', 'Tswana', 'Setswana'],
  ['tcy', 'Tulu', 'Tulu'],
  ['aeb', 'Tunisian Arabic', 'Tunisian Arabic'],
  ['tr', 'Turkish', 'Türkçe'],
  ['tk', 'Turkmen', 'türkmen dili'],
  ['uk', 'Ukrainian', 'українська'],
  ['hsb', 'Upper Sorbian', 'hornjoserbšćina'],
  ['ur', 'Urdu', 'اردو'],
  ['ug', 'Uyghur', 'ئۇيغۇرچە'],
  ['uz', 'Uzbek', 'o‘zbek'],
  ['ve', 'Venda', 'Venda'],
  ['vec', 'Venetian', 'veneto'],
  ['vi', 'Vietnamese', 'Tiếng Việt'],
  ['vo', 'Volapük', 'Volapük'],
  ['wa', 'Walloon', 'Walloon'],
  ['war', 'Waray', 'Waray'],
  ['cy', 'Welsh', 'Cymraeg'],
  ['vls', 'West Flemish', 'West Flemish'],
  ['fy', 'Western Frisian', 'Frysk'],
  ['wo', 'Wolof', 'Wolof'],
  ['wuu', 'Wu Chinese', 'Wu Chinese'],
  ['xh', 'Xhosa', 'IsiXhosa'],
  ['hsn', 'Xiang Chinese', 'Xiang Chinese'],
  ['yap', 'Yapese', 'Yapese'],
  ['ji', 'Yiddish', 'ייִדיש'],
  ['yi', 'Yiddish', 'ייִדיש'],
  ['yo', 'Yoruba', 'Èdè Yorùbá'],
  ['zea', 'Zeelandic', 'Zeelandic'],
  ['za', 'Zhuang', 'Vahcuengh'],
  ['zu', 'Zulu', 'isiZulu'],
  ];
  const LANGUAGES = ROWS.map(([code, name, native]) => Object.freeze({ code, name, native }));

  // Case-insensitive lookup by tag, English name, or native name, so a value
  // saved by an older build still resolves. A colliding name (several languages
  // share one) must resolve to the SAME row every time, or a search result and a
  // later lookup would disagree: keep the first row that claims a key.
  const INDEX = new Map();
  for (const language of LANGUAGES) {
    for (const key of [language.code, language.name, language.native]) {
      INDEX.set(key.toLowerCase(), language);
    }
  }

  const DEFAULT_TARGETS = Object.freeze(['en', 'es', 'fr', 'de', 'pt', 'it', 'zh-Hans', 'ja', 'ar', 'hi']);

  function get(code) {
    return (code && INDEX.get(String(code).toLowerCase())) || null;
  }

  function displayName(code, inLocale) {
    const language = get(code);
    if (!language) return code ? String(code) : '';
    try {
      const localized = new Intl.DisplayNames([inLocale || 'en'], { type: 'language' }).of(language.code);
      if (localized && localized.toLowerCase() !== language.code.toLowerCase()) return localized;
    } catch { /* fall through to the catalog name */ }
    return language.name;
  }

  // Languages whose name or native name starts with the query, then contains it.
  // Empty query returns the head of the alphabetical list.
  function search(query, limit = 60) {
    const needle = String(query || '').trim().toLowerCase();
    if (!needle) return LANGUAGES.slice(0, limit);
    /* An exact tag/name hit ranks first, resolved through the index rather than
     * the scan: the scan stops once it has enough rows, so a match later in the
     * alphabet (Spanish for "es", after Esperanto) would never be reached. */
    const hit = INDEX.get(needle);
    const exact = hit ? [hit] : [];
    const starts = [];
    const contains = [];
    for (const language of LANGUAGES) {
      if (language === hit) continue;
      const code = language.code.toLowerCase();
      const name = language.name.toLowerCase();
      const native = language.native.toLowerCase();
      if (name.startsWith(needle) || native.startsWith(needle) || code.startsWith(needle)) starts.push(language);
      else if (name.includes(needle) || native.includes(needle) || code.includes(needle)) contains.push(language);
      if (starts.length + contains.length > limit * 4) break;
    }
    return [...exact, ...starts, ...contains].slice(0, limit);
  }

  return Object.freeze({ LANGUAGES, DEFAULT_TARGETS, get, displayName, search });
});
